// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: couchbase/routing/v2/routing.proto

package routing_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRoutingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the specific bucket that will be accessed.
	BucketName    *string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3,oneof" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoutingRequest) Reset() {
	*x = WatchRoutingRequest{}
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingRequest) ProtoMessage() {}

func (x *WatchRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingRequest.ProtoReflect.Descriptor instead.
func (*WatchRoutingRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v2_routing_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRoutingRequest) GetBucketName() string {
	if x != nil && x.BucketName != nil {
		return *x.BucketName
	}
	return ""
}

type ServerRouting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumLocalServers uint32                 `protobuf:"varint,1,opt,name=num_local_servers,json=numLocalServers,proto3" json:"num_local_servers,omitempty"`
	NumGroupServers uint32                 `protobuf:"varint,2,opt,name=num_group_servers,json=numGroupServers,proto3" json:"num_group_servers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerRouting) Reset() {
	*x = ServerRouting{}
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRouting) ProtoMessage() {}

func (x *ServerRouting) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRouting.ProtoReflect.Descriptor instead.
func (*ServerRouting) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v2_routing_proto_rawDescGZIP(), []int{1}
}

func (x *ServerRouting) GetNumLocalServers() uint32 {
	if x != nil {
		return x.NumLocalServers
	}
	return 0
}

func (x *ServerRouting) GetNumGroupServers() uint32 {
	if x != nil {
		return x.NumGroupServers
	}
	return 0
}

type VbucketRouting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumVbuckets   uint32                 `protobuf:"varint,1,opt,name=num_vbuckets,json=numVbuckets,proto3" json:"num_vbuckets,omitempty"`
	LocalVbuckets []uint32               `protobuf:"varint,2,rep,packed,name=local_vbuckets,json=localVbuckets,proto3" json:"local_vbuckets,omitempty"`
	GroupVbuckets []uint32               `protobuf:"varint,3,rep,packed,name=group_vbuckets,json=groupVbuckets,proto3" json:"group_vbuckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VbucketRouting) Reset() {
	*x = VbucketRouting{}
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VbucketRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VbucketRouting) ProtoMessage() {}

func (x *VbucketRouting) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VbucketRouting.ProtoReflect.Descriptor instead.
func (*VbucketRouting) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v2_routing_proto_rawDescGZIP(), []int{2}
}

func (x *VbucketRouting) GetNumVbuckets() uint32 {
	if x != nil {
		return x.NumVbuckets
	}
	return 0
}

func (x *VbucketRouting) GetLocalVbuckets() []uint32 {
	if x != nil {
		return x.LocalVbuckets
	}
	return nil
}

func (x *VbucketRouting) GetGroupVbuckets() []uint32 {
	if x != nil {
		return x.GroupVbuckets
	}
	return nil
}

type WatchRoutingResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerRouting      *ServerRouting         `protobuf:"bytes,1,opt,name=server_routing,json=serverRouting,proto3,oneof" json:"server_routing,omitempty"`
	ViewsRouting       *ServerRouting         `protobuf:"bytes,2,opt,name=views_routing,json=viewsRouting,proto3,oneof" json:"views_routing,omitempty"`
	QueryRouting       *ServerRouting         `protobuf:"bytes,3,opt,name=query_routing,json=queryRouting,proto3,oneof" json:"query_routing,omitempty"`
	SearchRouting      *ServerRouting         `protobuf:"bytes,4,opt,name=search_routing,json=searchRouting,proto3,oneof" json:"search_routing,omitempty"`
	AnalyticsRouting   *ServerRouting         `protobuf:"bytes,5,opt,name=analytics_routing,json=analyticsRouting,proto3,oneof" json:"analytics_routing,omitempty"`
	VbucketDataRouting *VbucketRouting        `protobuf:"bytes,6,opt,name=vbucket_data_routing,json=vbucketDataRouting,proto3,oneof" json:"vbucket_data_routing,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchRoutingResponse) Reset() {
	*x = WatchRoutingResponse{}
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingResponse) ProtoMessage() {}

func (x *WatchRoutingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v2_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingResponse.ProtoReflect.Descriptor instead.
func (*WatchRoutingResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v2_routing_proto_rawDescGZIP(), []int{3}
}

func (x *WatchRoutingResponse) GetServerRouting() *ServerRouting {
	if x != nil {
		return x.ServerRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetViewsRouting() *ServerRouting {
	if x != nil {
		return x.ViewsRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetQueryRouting() *ServerRouting {
	if x != nil {
		return x.QueryRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetSearchRouting() *ServerRouting {
	if x != nil {
		return x.SearchRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetAnalyticsRouting() *ServerRouting {
	if x != nil {
		return x.AnalyticsRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetVbucketDataRouting() *VbucketRouting {
	if x != nil {
		return x.VbucketDataRouting
	}
	return nil
}

var File_couchbase_routing_v2_routing_proto protoreflect.FileDescriptor

const file_couchbase_routing_v2_routing_proto_rawDesc = "" +
	"\n" +
	"\"couchbase/routing/v2/routing.proto\x12\x14couchbase.routing.v2\"K\n" +
	"\x13WatchRoutingRequest\x12$\n" +
	"\vbucket_name\x18\x01 \x01(\tH\x00R\n" +
	"bucketName\x88\x01\x01B\x0e\n" +
	"\f_bucket_name\"g\n" +
	"\rServerRouting\x12*\n" +
	"\x11num_local_servers\x18\x01 \x01(\rR\x0fnumLocalServers\x12*\n" +
	"\x11num_group_servers\x18\x02 \x01(\rR\x0fnumGroupServers\"\x81\x01\n" +
	"\x0eVbucketRouting\x12!\n" +
	"\fnum_vbuckets\x18\x01 \x01(\rR\vnumVbuckets\x12%\n" +
	"\x0elocal_vbuckets\x18\x02 \x03(\rR\rlocalVbuckets\x12%\n" +
	"\x0egroup_vbuckets\x18\x03 \x03(\rR\rgroupVbuckets\"\x83\x05\n" +
	"\x14WatchRoutingResponse\x12O\n" +
	"\x0eserver_routing\x18\x01 \x01(\v2#.couchbase.routing.v2.ServerRoutingH\x00R\rserverRouting\x88\x01\x01\x12M\n" +
	"\rviews_routing\x18\x02 \x01(\v2#.couchbase.routing.v2.ServerRoutingH\x01R\fviewsRouting\x88\x01\x01\x12M\n" +
	"\rquery_routing\x18\x03 \x01(\v2#.couchbase.routing.v2.ServerRoutingH\x02R\fqueryRouting\x88\x01\x01\x12O\n" +
	"\x0esearch_routing\x18\x04 \x01(\v2#.couchbase.routing.v2.ServerRoutingH\x03R\rsearchRouting\x88\x01\x01\x12U\n" +
	"\x11analytics_routing\x18\x05 \x01(\v2#.couchbase.routing.v2.ServerRoutingH\x04R\x10analyticsRouting\x88\x01\x01\x12[\n" +
	"\x14vbucket_data_routing\x18\x06 \x01(\v2$.couchbase.routing.v2.VbucketRoutingH\x05R\x12vbucketDataRouting\x88\x01\x01B\x11\n" +
	"\x0f_server_routingB\x10\n" +
	"\x0e_views_routingB\x10\n" +
	"\x0e_query_routingB\x11\n" +
	"\x0f_search_routingB\x14\n" +
	"\x12_analytics_routingB\x17\n" +
	"\x15_vbucket_data_routing2{\n" +
	"\x0eRoutingService\x12i\n" +
	"\fWatchRouting\x12).couchbase.routing.v2.WatchRoutingRequest\x1a*.couchbase.routing.v2.WatchRoutingResponse\"\x000\x01B\xf8\x01\n" +
	",com.couchbase.client.protostellar.routing.v2P\x01ZBgithub.com/couchbase/goprotostellar/genproto/routing_v2;routing_v2\xaa\x02!Couchbase.Protostellar.Routing.V2\xca\x02+Couchbase\\Protostellar\\Generated\\Routing\\V2\xea\x02/Couchbase::Protostellar::Generated::Routing::V2b\x06proto3"

var (
	file_couchbase_routing_v2_routing_proto_rawDescOnce sync.Once
	file_couchbase_routing_v2_routing_proto_rawDescData []byte
)

func file_couchbase_routing_v2_routing_proto_rawDescGZIP() []byte {
	file_couchbase_routing_v2_routing_proto_rawDescOnce.Do(func() {
		file_couchbase_routing_v2_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couchbase_routing_v2_routing_proto_rawDesc), len(file_couchbase_routing_v2_routing_proto_rawDesc)))
	})
	return file_couchbase_routing_v2_routing_proto_rawDescData
}

var file_couchbase_routing_v2_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_couchbase_routing_v2_routing_proto_goTypes = []any{
	(*WatchRoutingRequest)(nil),  // 0: couchbase.routing.v2.WatchRoutingRequest
	(*ServerRouting)(nil),        // 1: couchbase.routing.v2.ServerRouting
	(*VbucketRouting)(nil),       // 2: couchbase.routing.v2.VbucketRouting
	(*WatchRoutingResponse)(nil), // 3: couchbase.routing.v2.WatchRoutingResponse
}
var file_couchbase_routing_v2_routing_proto_depIdxs = []int32{
	1, // 0: couchbase.routing.v2.WatchRoutingResponse.server_routing:type_name -> couchbase.routing.v2.ServerRouting
	1, // 1: couchbase.routing.v2.WatchRoutingResponse.views_routing:type_name -> couchbase.routing.v2.ServerRouting
	1, // 2: couchbase.routing.v2.WatchRoutingResponse.query_routing:type_name -> couchbase.routing.v2.ServerRouting
	1, // 3: couchbase.routing.v2.WatchRoutingResponse.search_routing:type_name -> couchbase.routing.v2.ServerRouting
	1, // 4: couchbase.routing.v2.WatchRoutingResponse.analytics_routing:type_name -> couchbase.routing.v2.ServerRouting
	2, // 5: couchbase.routing.v2.WatchRoutingResponse.vbucket_data_routing:type_name -> couchbase.routing.v2.VbucketRouting
	0, // 6: couchbase.routing.v2.RoutingService.WatchRouting:input_type -> couchbase.routing.v2.WatchRoutingRequest
	3, // 7: couchbase.routing.v2.RoutingService.WatchRouting:output_type -> couchbase.routing.v2.WatchRoutingResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_couchbase_routing_v2_routing_proto_init() }
func file_couchbase_routing_v2_routing_proto_init() {
	if File_couchbase_routing_v2_routing_proto != nil {
		return
	}
	file_couchbase_routing_v2_routing_proto_msgTypes[0].OneofWrappers = []any{}
	file_couchbase_routing_v2_routing_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couchbase_routing_v2_routing_proto_rawDesc), len(file_couchbase_routing_v2_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couchbase_routing_v2_routing_proto_goTypes,
		DependencyIndexes: file_couchbase_routing_v2_routing_proto_depIdxs,
		MessageInfos:      file_couchbase_routing_v2_routing_proto_msgTypes,
	}.Build()
	File_couchbase_routing_v2_routing_proto = out.File
	file_couchbase_routing_v2_routing_proto_goTypes = nil
	file_couchbase_routing_v2_routing_proto_depIdxs = nil
}
