// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: couchbase/transactions/v1/transactions.proto

package transactions_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionBeginAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	TransactionId *string                `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3,oneof" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBeginAttemptRequest) Reset() {
	*x = TransactionBeginAttemptRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBeginAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBeginAttemptRequest) ProtoMessage() {}

func (x *TransactionBeginAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBeginAttemptRequest.ProtoReflect.Descriptor instead.
func (*TransactionBeginAttemptRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionBeginAttemptRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionBeginAttemptRequest) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

type TransactionBeginAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBeginAttemptResponse) Reset() {
	*x = TransactionBeginAttemptResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBeginAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBeginAttemptResponse) ProtoMessage() {}

func (x *TransactionBeginAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBeginAttemptResponse.ProtoReflect.Descriptor instead.
func (*TransactionBeginAttemptResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionBeginAttemptResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionBeginAttemptResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type TransactionCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionCommitRequest) Reset() {
	*x = TransactionCommitRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCommitRequest) ProtoMessage() {}

func (x *TransactionCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCommitRequest.ProtoReflect.Descriptor instead.
func (*TransactionCommitRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionCommitRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionCommitRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionCommitRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type TransactionCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionCommitResponse) Reset() {
	*x = TransactionCommitResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCommitResponse) ProtoMessage() {}

func (x *TransactionCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCommitResponse.ProtoReflect.Descriptor instead.
func (*TransactionCommitResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{3}
}

type TransactionRollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRollbackRequest) Reset() {
	*x = TransactionRollbackRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRollbackRequest) ProtoMessage() {}

func (x *TransactionRollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRollbackRequest.ProtoReflect.Descriptor instead.
func (*TransactionRollbackRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionRollbackRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionRollbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRollbackRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type TransactionRollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRollbackResponse) Reset() {
	*x = TransactionRollbackResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRollbackResponse) ProtoMessage() {}

func (x *TransactionRollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRollbackResponse.ProtoReflect.Descriptor instead.
func (*TransactionRollbackResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{5}
}

type TransactionGetRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BucketName string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// transaction_id and attempt_id are optional to allow read-only transactions.
	// clients are not permitted to use this functionality to optimize
	// non-read-only transactions.
	TransactionId  string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId      string `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ScopeName      string `protobuf:"bytes,4,opt,name=scope_name,json=scopeName,proto3" json:"scope_name,omitempty"`
	CollectionName string `protobuf:"bytes,5,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Key            string `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionGetRequest) Reset() {
	*x = TransactionGetRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionGetRequest) ProtoMessage() {}

func (x *TransactionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionGetRequest.ProtoReflect.Descriptor instead.
func (*TransactionGetRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionGetRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionGetRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionGetRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TransactionGetRequest) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *TransactionGetRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *TransactionGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TransactionGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cas           uint64                 `protobuf:"varint,1,opt,name=cas,proto3" json:"cas,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionGetResponse) Reset() {
	*x = TransactionGetResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionGetResponse) ProtoMessage() {}

func (x *TransactionGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionGetResponse.ProtoReflect.Descriptor instead.
func (*TransactionGetResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionGetResponse) GetCas() uint64 {
	if x != nil {
		return x.Cas
	}
	return 0
}

func (x *TransactionGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type TransactionInsertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketName     string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ScopeName      string                 `protobuf:"bytes,4,opt,name=scope_name,json=scopeName,proto3" json:"scope_name,omitempty"`
	CollectionName string                 `protobuf:"bytes,5,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Key            string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionInsertRequest) Reset() {
	*x = TransactionInsertRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInsertRequest) ProtoMessage() {}

func (x *TransactionInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInsertRequest.ProtoReflect.Descriptor instead.
func (*TransactionInsertRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionInsertRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionInsertRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionInsertRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TransactionInsertRequest) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *TransactionInsertRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *TransactionInsertRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TransactionInsertRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type TransactionInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cas           uint64                 `protobuf:"varint,1,opt,name=cas,proto3" json:"cas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInsertResponse) Reset() {
	*x = TransactionInsertResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInsertResponse) ProtoMessage() {}

func (x *TransactionInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInsertResponse.ProtoReflect.Descriptor instead.
func (*TransactionInsertResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionInsertResponse) GetCas() uint64 {
	if x != nil {
		return x.Cas
	}
	return 0
}

type TransactionReplaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketName     string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ScopeName      string                 `protobuf:"bytes,4,opt,name=scope_name,json=scopeName,proto3" json:"scope_name,omitempty"`
	CollectionName string                 `protobuf:"bytes,5,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Key            string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Cas            uint64                 `protobuf:"varint,7,opt,name=cas,proto3" json:"cas,omitempty"`
	Value          []byte                 `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionReplaceRequest) Reset() {
	*x = TransactionReplaceRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReplaceRequest) ProtoMessage() {}

func (x *TransactionReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReplaceRequest.ProtoReflect.Descriptor instead.
func (*TransactionReplaceRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionReplaceRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionReplaceRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionReplaceRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TransactionReplaceRequest) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *TransactionReplaceRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *TransactionReplaceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TransactionReplaceRequest) GetCas() uint64 {
	if x != nil {
		return x.Cas
	}
	return 0
}

func (x *TransactionReplaceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type TransactionReplaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cas           uint64                 `protobuf:"varint,1,opt,name=cas,proto3" json:"cas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionReplaceResponse) Reset() {
	*x = TransactionReplaceResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReplaceResponse) ProtoMessage() {}

func (x *TransactionReplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReplaceResponse.ProtoReflect.Descriptor instead.
func (*TransactionReplaceResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionReplaceResponse) GetCas() uint64 {
	if x != nil {
		return x.Cas
	}
	return 0
}

type TransactionRemoveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketName     string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ScopeName      string                 `protobuf:"bytes,4,opt,name=scope_name,json=scopeName,proto3" json:"scope_name,omitempty"`
	CollectionName string                 `protobuf:"bytes,5,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Key            string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Cas            uint64                 `protobuf:"varint,7,opt,name=cas,proto3" json:"cas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionRemoveRequest) Reset() {
	*x = TransactionRemoveRequest{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRemoveRequest) ProtoMessage() {}

func (x *TransactionRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRemoveRequest.ProtoReflect.Descriptor instead.
func (*TransactionRemoveRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionRemoveRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *TransactionRemoveRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRemoveRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TransactionRemoveRequest) GetScopeName() string {
	if x != nil {
		return x.ScopeName
	}
	return ""
}

func (x *TransactionRemoveRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *TransactionRemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TransactionRemoveRequest) GetCas() uint64 {
	if x != nil {
		return x.Cas
	}
	return 0
}

type TransactionRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cas           uint64                 `protobuf:"varint,1,opt,name=cas,proto3" json:"cas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRemoveResponse) Reset() {
	*x = TransactionRemoveResponse{}
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRemoveResponse) ProtoMessage() {}

func (x *TransactionRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_transactions_v1_transactions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRemoveResponse.ProtoReflect.Descriptor instead.
func (*TransactionRemoveResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_transactions_v1_transactions_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionRemoveResponse) GetCas() uint64 {
	if x != nil {
		return x.Cas
	}
	return 0
}

var File_couchbase_transactions_v1_transactions_proto protoreflect.FileDescriptor

const file_couchbase_transactions_v1_transactions_proto_rawDesc = "" +
	"\n" +
	",couchbase/transactions/v1/transactions.proto\x12\x19couchbase.transactions.v1\"\x80\x01\n" +
	"\x1eTransactionBeginAttemptRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12*\n" +
	"\x0etransaction_id\x18\x02 \x01(\tH\x00R\rtransactionId\x88\x01\x01B\x11\n" +
	"\x0f_transaction_id\"g\n" +
	"\x1fTransactionBeginAttemptResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\"\x81\x01\n" +
	"\x18TransactionCommitRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\"\x1b\n" +
	"\x19TransactionCommitResponse\"\x83\x01\n" +
	"\x1aTransactionRollbackRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\"\x1d\n" +
	"\x1bTransactionRollbackResponse\"\xd8\x01\n" +
	"\x15TransactionGetRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1d\n" +
	"\n" +
	"scope_name\x18\x04 \x01(\tR\tscopeName\x12'\n" +
	"\x0fcollection_name\x18\x05 \x01(\tR\x0ecollectionName\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\"@\n" +
	"\x16TransactionGetResponse\x12\x10\n" +
	"\x03cas\x18\x01 \x01(\x04R\x03cas\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xf1\x01\n" +
	"\x18TransactionInsertRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1d\n" +
	"\n" +
	"scope_name\x18\x04 \x01(\tR\tscopeName\x12'\n" +
	"\x0fcollection_name\x18\x05 \x01(\tR\x0ecollectionName\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\"-\n" +
	"\x19TransactionInsertResponse\x12\x10\n" +
	"\x03cas\x18\x01 \x01(\x04R\x03cas\"\x84\x02\n" +
	"\x19TransactionReplaceRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1d\n" +
	"\n" +
	"scope_name\x18\x04 \x01(\tR\tscopeName\x12'\n" +
	"\x0fcollection_name\x18\x05 \x01(\tR\x0ecollectionName\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x10\n" +
	"\x03cas\x18\a \x01(\x04R\x03cas\x12\x14\n" +
	"\x05value\x18\b \x01(\fR\x05value\".\n" +
	"\x1aTransactionReplaceResponse\x12\x10\n" +
	"\x03cas\x18\x01 \x01(\x04R\x03cas\"\xed\x01\n" +
	"\x18TransactionRemoveRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1d\n" +
	"\n" +
	"scope_name\x18\x04 \x01(\tR\tscopeName\x12'\n" +
	"\x0fcollection_name\x18\x05 \x01(\tR\x0ecollectionName\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x10\n" +
	"\x03cas\x18\a \x01(\x04R\x03cas\"-\n" +
	"\x19TransactionRemoveResponse\x12\x10\n" +
	"\x03cas\x18\x01 \x01(\x04R\x03cas2\xbb\a\n" +
	"\x13TransactionsService\x12\x92\x01\n" +
	"\x17TransactionBeginAttempt\x129.couchbase.transactions.v1.TransactionBeginAttemptRequest\x1a:.couchbase.transactions.v1.TransactionBeginAttemptResponse\"\x00\x12\x80\x01\n" +
	"\x11TransactionCommit\x123.couchbase.transactions.v1.TransactionCommitRequest\x1a4.couchbase.transactions.v1.TransactionCommitResponse\"\x00\x12\x86\x01\n" +
	"\x13TransactionRollback\x125.couchbase.transactions.v1.TransactionRollbackRequest\x1a6.couchbase.transactions.v1.TransactionRollbackResponse\"\x00\x12w\n" +
	"\x0eTransactionGet\x120.couchbase.transactions.v1.TransactionGetRequest\x1a1.couchbase.transactions.v1.TransactionGetResponse\"\x00\x12\x80\x01\n" +
	"\x11TransactionInsert\x123.couchbase.transactions.v1.TransactionInsertRequest\x1a4.couchbase.transactions.v1.TransactionInsertResponse\"\x00\x12\x83\x01\n" +
	"\x12TransactionReplace\x124.couchbase.transactions.v1.TransactionReplaceRequest\x1a5.couchbase.transactions.v1.TransactionReplaceResponse\"\x00\x12\x80\x01\n" +
	"\x11TransactionRemove\x123.couchbase.transactions.v1.TransactionRemoveRequest\x1a4.couchbase.transactions.v1.TransactionRemoveResponse\"\x00B\x96\x02\n" +
	"1com.couchbase.client.protostellar.transactions.v1P\x01ZLgithub.com/couchbase/goprotostellar/genproto/transactions_v1;transactions_v1\xaa\x02&Couchbase.Protostellar.Transactions.V1\xca\x020Couchbase\\Protostellar\\Generated\\Transactions\\V1\xea\x024Couchbase::Protostellar::Generated::Transactions::V1b\x06proto3"

var (
	file_couchbase_transactions_v1_transactions_proto_rawDescOnce sync.Once
	file_couchbase_transactions_v1_transactions_proto_rawDescData []byte
)

func file_couchbase_transactions_v1_transactions_proto_rawDescGZIP() []byte {
	file_couchbase_transactions_v1_transactions_proto_rawDescOnce.Do(func() {
		file_couchbase_transactions_v1_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couchbase_transactions_v1_transactions_proto_rawDesc), len(file_couchbase_transactions_v1_transactions_proto_rawDesc)))
	})
	return file_couchbase_transactions_v1_transactions_proto_rawDescData
}

var file_couchbase_transactions_v1_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_couchbase_transactions_v1_transactions_proto_goTypes = []any{
	(*TransactionBeginAttemptRequest)(nil),  // 0: couchbase.transactions.v1.TransactionBeginAttemptRequest
	(*TransactionBeginAttemptResponse)(nil), // 1: couchbase.transactions.v1.TransactionBeginAttemptResponse
	(*TransactionCommitRequest)(nil),        // 2: couchbase.transactions.v1.TransactionCommitRequest
	(*TransactionCommitResponse)(nil),       // 3: couchbase.transactions.v1.TransactionCommitResponse
	(*TransactionRollbackRequest)(nil),      // 4: couchbase.transactions.v1.TransactionRollbackRequest
	(*TransactionRollbackResponse)(nil),     // 5: couchbase.transactions.v1.TransactionRollbackResponse
	(*TransactionGetRequest)(nil),           // 6: couchbase.transactions.v1.TransactionGetRequest
	(*TransactionGetResponse)(nil),          // 7: couchbase.transactions.v1.TransactionGetResponse
	(*TransactionInsertRequest)(nil),        // 8: couchbase.transactions.v1.TransactionInsertRequest
	(*TransactionInsertResponse)(nil),       // 9: couchbase.transactions.v1.TransactionInsertResponse
	(*TransactionReplaceRequest)(nil),       // 10: couchbase.transactions.v1.TransactionReplaceRequest
	(*TransactionReplaceResponse)(nil),      // 11: couchbase.transactions.v1.TransactionReplaceResponse
	(*TransactionRemoveRequest)(nil),        // 12: couchbase.transactions.v1.TransactionRemoveRequest
	(*TransactionRemoveResponse)(nil),       // 13: couchbase.transactions.v1.TransactionRemoveResponse
}
var file_couchbase_transactions_v1_transactions_proto_depIdxs = []int32{
	0,  // 0: couchbase.transactions.v1.TransactionsService.TransactionBeginAttempt:input_type -> couchbase.transactions.v1.TransactionBeginAttemptRequest
	2,  // 1: couchbase.transactions.v1.TransactionsService.TransactionCommit:input_type -> couchbase.transactions.v1.TransactionCommitRequest
	4,  // 2: couchbase.transactions.v1.TransactionsService.TransactionRollback:input_type -> couchbase.transactions.v1.TransactionRollbackRequest
	6,  // 3: couchbase.transactions.v1.TransactionsService.TransactionGet:input_type -> couchbase.transactions.v1.TransactionGetRequest
	8,  // 4: couchbase.transactions.v1.TransactionsService.TransactionInsert:input_type -> couchbase.transactions.v1.TransactionInsertRequest
	10, // 5: couchbase.transactions.v1.TransactionsService.TransactionReplace:input_type -> couchbase.transactions.v1.TransactionReplaceRequest
	12, // 6: couchbase.transactions.v1.TransactionsService.TransactionRemove:input_type -> couchbase.transactions.v1.TransactionRemoveRequest
	1,  // 7: couchbase.transactions.v1.TransactionsService.TransactionBeginAttempt:output_type -> couchbase.transactions.v1.TransactionBeginAttemptResponse
	3,  // 8: couchbase.transactions.v1.TransactionsService.TransactionCommit:output_type -> couchbase.transactions.v1.TransactionCommitResponse
	5,  // 9: couchbase.transactions.v1.TransactionsService.TransactionRollback:output_type -> couchbase.transactions.v1.TransactionRollbackResponse
	7,  // 10: couchbase.transactions.v1.TransactionsService.TransactionGet:output_type -> couchbase.transactions.v1.TransactionGetResponse
	9,  // 11: couchbase.transactions.v1.TransactionsService.TransactionInsert:output_type -> couchbase.transactions.v1.TransactionInsertResponse
	11, // 12: couchbase.transactions.v1.TransactionsService.TransactionReplace:output_type -> couchbase.transactions.v1.TransactionReplaceResponse
	13, // 13: couchbase.transactions.v1.TransactionsService.TransactionRemove:output_type -> couchbase.transactions.v1.TransactionRemoveResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_couchbase_transactions_v1_transactions_proto_init() }
func file_couchbase_transactions_v1_transactions_proto_init() {
	if File_couchbase_transactions_v1_transactions_proto != nil {
		return
	}
	file_couchbase_transactions_v1_transactions_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couchbase_transactions_v1_transactions_proto_rawDesc), len(file_couchbase_transactions_v1_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couchbase_transactions_v1_transactions_proto_goTypes,
		DependencyIndexes: file_couchbase_transactions_v1_transactions_proto_depIdxs,
		MessageInfos:      file_couchbase_transactions_v1_transactions_proto_msgTypes,
	}.Build()
	File_couchbase_transactions_v1_transactions_proto = out.File
	file_couchbase_transactions_v1_transactions_proto_goTypes = nil
	file_couchbase_transactions_v1_transactions_proto_depIdxs = nil
}
