// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: couchbase/internal/hooks/v1/hooks.proto

package internal_hooks_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HooksService_CreateHooksContext_FullMethodName  = "/couchbase.internal.hooks.v1.HooksService/CreateHooksContext"
	HooksService_DestroyHooksContext_FullMethodName = "/couchbase.internal.hooks.v1.HooksService/DestroyHooksContext"
	HooksService_AddHooks_FullMethodName            = "/couchbase.internal.hooks.v1.HooksService/AddHooks"
	HooksService_WatchBarrier_FullMethodName        = "/couchbase.internal.hooks.v1.HooksService/WatchBarrier"
	HooksService_SignalBarrier_FullMethodName       = "/couchbase.internal.hooks.v1.HooksService/SignalBarrier"
	HooksService_WatchRequests_FullMethodName       = "/couchbase.internal.hooks.v1.HooksService/WatchRequests"
)

// HooksServiceClient is the client API for HooksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HooksServiceClient interface {
	CreateHooksContext(ctx context.Context, in *CreateHooksContextRequest, opts ...grpc.CallOption) (*CreateHooksContextResponse, error)
	DestroyHooksContext(ctx context.Context, in *DestroyHooksContextRequest, opts ...grpc.CallOption) (*DestroyHooksContextResponse, error)
	AddHooks(ctx context.Context, in *AddHooksRequest, opts ...grpc.CallOption) (*AddHooksResponse, error)
	WatchBarrier(ctx context.Context, in *WatchBarrierRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchBarrierResponse], error)
	SignalBarrier(ctx context.Context, in *SignalBarrierRequest, opts ...grpc.CallOption) (*SignalBarrierResponse, error)
	WatchRequests(ctx context.Context, in *WatchRequestsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRequestsResponse], error)
}

type hooksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHooksServiceClient(cc grpc.ClientConnInterface) HooksServiceClient {
	return &hooksServiceClient{cc}
}

func (c *hooksServiceClient) CreateHooksContext(ctx context.Context, in *CreateHooksContextRequest, opts ...grpc.CallOption) (*CreateHooksContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHooksContextResponse)
	err := c.cc.Invoke(ctx, HooksService_CreateHooksContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) DestroyHooksContext(ctx context.Context, in *DestroyHooksContextRequest, opts ...grpc.CallOption) (*DestroyHooksContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyHooksContextResponse)
	err := c.cc.Invoke(ctx, HooksService_DestroyHooksContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) AddHooks(ctx context.Context, in *AddHooksRequest, opts ...grpc.CallOption) (*AddHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHooksResponse)
	err := c.cc.Invoke(ctx, HooksService_AddHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) WatchBarrier(ctx context.Context, in *WatchBarrierRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchBarrierResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HooksService_ServiceDesc.Streams[0], HooksService_WatchBarrier_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchBarrierRequest, WatchBarrierResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HooksService_WatchBarrierClient = grpc.ServerStreamingClient[WatchBarrierResponse]

func (c *hooksServiceClient) SignalBarrier(ctx context.Context, in *SignalBarrierRequest, opts ...grpc.CallOption) (*SignalBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalBarrierResponse)
	err := c.cc.Invoke(ctx, HooksService_SignalBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hooksServiceClient) WatchRequests(ctx context.Context, in *WatchRequestsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRequestsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HooksService_ServiceDesc.Streams[1], HooksService_WatchRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequestsRequest, WatchRequestsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HooksService_WatchRequestsClient = grpc.ServerStreamingClient[WatchRequestsResponse]

// HooksServiceServer is the server API for HooksService service.
// All implementations must embed UnimplementedHooksServiceServer
// for forward compatibility.
type HooksServiceServer interface {
	CreateHooksContext(context.Context, *CreateHooksContextRequest) (*CreateHooksContextResponse, error)
	DestroyHooksContext(context.Context, *DestroyHooksContextRequest) (*DestroyHooksContextResponse, error)
	AddHooks(context.Context, *AddHooksRequest) (*AddHooksResponse, error)
	WatchBarrier(*WatchBarrierRequest, grpc.ServerStreamingServer[WatchBarrierResponse]) error
	SignalBarrier(context.Context, *SignalBarrierRequest) (*SignalBarrierResponse, error)
	WatchRequests(*WatchRequestsRequest, grpc.ServerStreamingServer[WatchRequestsResponse]) error
	mustEmbedUnimplementedHooksServiceServer()
}

// UnimplementedHooksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHooksServiceServer struct{}

func (UnimplementedHooksServiceServer) CreateHooksContext(context.Context, *CreateHooksContextRequest) (*CreateHooksContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHooksContext not implemented")
}
func (UnimplementedHooksServiceServer) DestroyHooksContext(context.Context, *DestroyHooksContextRequest) (*DestroyHooksContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyHooksContext not implemented")
}
func (UnimplementedHooksServiceServer) AddHooks(context.Context, *AddHooksRequest) (*AddHooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHooks not implemented")
}
func (UnimplementedHooksServiceServer) WatchBarrier(*WatchBarrierRequest, grpc.ServerStreamingServer[WatchBarrierResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchBarrier not implemented")
}
func (UnimplementedHooksServiceServer) SignalBarrier(context.Context, *SignalBarrierRequest) (*SignalBarrierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalBarrier not implemented")
}
func (UnimplementedHooksServiceServer) WatchRequests(*WatchRequestsRequest, grpc.ServerStreamingServer[WatchRequestsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRequests not implemented")
}
func (UnimplementedHooksServiceServer) mustEmbedUnimplementedHooksServiceServer() {}
func (UnimplementedHooksServiceServer) testEmbeddedByValue()                      {}

// UnsafeHooksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HooksServiceServer will
// result in compilation errors.
type UnsafeHooksServiceServer interface {
	mustEmbedUnimplementedHooksServiceServer()
}

func RegisterHooksServiceServer(s grpc.ServiceRegistrar, srv HooksServiceServer) {
	// If the following call pancis, it indicates UnimplementedHooksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HooksService_ServiceDesc, srv)
}

func _HooksService_CreateHooksContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHooksContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).CreateHooksContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HooksService_CreateHooksContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).CreateHooksContext(ctx, req.(*CreateHooksContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_DestroyHooksContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyHooksContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).DestroyHooksContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HooksService_DestroyHooksContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).DestroyHooksContext(ctx, req.(*DestroyHooksContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_AddHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).AddHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HooksService_AddHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).AddHooks(ctx, req.(*AddHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_WatchBarrier_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchBarrierRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HooksServiceServer).WatchBarrier(m, &grpc.GenericServerStream[WatchBarrierRequest, WatchBarrierResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HooksService_WatchBarrierServer = grpc.ServerStreamingServer[WatchBarrierResponse]

func _HooksService_SignalBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HooksServiceServer).SignalBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HooksService_SignalBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HooksServiceServer).SignalBarrier(ctx, req.(*SignalBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HooksService_WatchRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequestsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HooksServiceServer).WatchRequests(m, &grpc.GenericServerStream[WatchRequestsRequest, WatchRequestsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HooksService_WatchRequestsServer = grpc.ServerStreamingServer[WatchRequestsResponse]

// HooksService_ServiceDesc is the grpc.ServiceDesc for HooksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HooksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "couchbase.internal.hooks.v1.HooksService",
	HandlerType: (*HooksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHooksContext",
			Handler:    _HooksService_CreateHooksContext_Handler,
		},
		{
			MethodName: "DestroyHooksContext",
			Handler:    _HooksService_DestroyHooksContext_Handler,
		},
		{
			MethodName: "AddHooks",
			Handler:    _HooksService_AddHooks_Handler,
		},
		{
			MethodName: "SignalBarrier",
			Handler:    _HooksService_SignalBarrier_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchBarrier",
			Handler:       _HooksService_WatchBarrier_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchRequests",
			Handler:       _HooksService_WatchRequests_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "couchbase/internal/hooks/v1/hooks.proto",
}
