// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: couchbase/admin/bucket/v1/bucket.proto

package admin_bucket_v1

import (
	kv_v1 "github.com/couchbase/goprotostellar/genproto/kv_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketType int32

const (
	BucketType_BUCKET_TYPE_COUCHBASE BucketType = 0
	BucketType_BUCKET_TYPE_EPHEMERAL BucketType = 1
)

// Enum value maps for BucketType.
var (
	BucketType_name = map[int32]string{
		0: "BUCKET_TYPE_COUCHBASE",
		1: "BUCKET_TYPE_EPHEMERAL",
	}
	BucketType_value = map[string]int32{
		"BUCKET_TYPE_COUCHBASE": 0,
		"BUCKET_TYPE_EPHEMERAL": 1,
	}
)

func (x BucketType) Enum() *BucketType {
	p := new(BucketType)
	*p = x
	return p
}

func (x BucketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BucketType) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[0].Descriptor()
}

func (BucketType) Type() protoreflect.EnumType {
	return &file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[0]
}

func (x BucketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BucketType.Descriptor instead.
func (BucketType) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{0}
}

type EvictionMode int32

const (
	EvictionMode_EVICTION_MODE_FULL              EvictionMode = 0
	EvictionMode_EVICTION_MODE_NOT_RECENTLY_USED EvictionMode = 1
	EvictionMode_EVICTION_MODE_VALUE_ONLY        EvictionMode = 2
	EvictionMode_EVICTION_MODE_NONE              EvictionMode = 3
)

// Enum value maps for EvictionMode.
var (
	EvictionMode_name = map[int32]string{
		0: "EVICTION_MODE_FULL",
		1: "EVICTION_MODE_NOT_RECENTLY_USED",
		2: "EVICTION_MODE_VALUE_ONLY",
		3: "EVICTION_MODE_NONE",
	}
	EvictionMode_value = map[string]int32{
		"EVICTION_MODE_FULL":              0,
		"EVICTION_MODE_NOT_RECENTLY_USED": 1,
		"EVICTION_MODE_VALUE_ONLY":        2,
		"EVICTION_MODE_NONE":              3,
	}
)

func (x EvictionMode) Enum() *EvictionMode {
	p := new(EvictionMode)
	*p = x
	return p
}

func (x EvictionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvictionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[1].Descriptor()
}

func (EvictionMode) Type() protoreflect.EnumType {
	return &file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[1]
}

func (x EvictionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvictionMode.Descriptor instead.
func (EvictionMode) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{1}
}

type CompressionMode int32

const (
	CompressionMode_COMPRESSION_MODE_OFF     CompressionMode = 0
	CompressionMode_COMPRESSION_MODE_PASSIVE CompressionMode = 1
	CompressionMode_COMPRESSION_MODE_ACTIVE  CompressionMode = 2
)

// Enum value maps for CompressionMode.
var (
	CompressionMode_name = map[int32]string{
		0: "COMPRESSION_MODE_OFF",
		1: "COMPRESSION_MODE_PASSIVE",
		2: "COMPRESSION_MODE_ACTIVE",
	}
	CompressionMode_value = map[string]int32{
		"COMPRESSION_MODE_OFF":     0,
		"COMPRESSION_MODE_PASSIVE": 1,
		"COMPRESSION_MODE_ACTIVE":  2,
	}
)

func (x CompressionMode) Enum() *CompressionMode {
	p := new(CompressionMode)
	*p = x
	return p
}

func (x CompressionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[2].Descriptor()
}

func (CompressionMode) Type() protoreflect.EnumType {
	return &file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[2]
}

func (x CompressionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionMode.Descriptor instead.
func (CompressionMode) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{2}
}

type StorageBackend int32

const (
	StorageBackend_STORAGE_BACKEND_COUCHSTORE StorageBackend = 0
	StorageBackend_STORAGE_BACKEND_MAGMA      StorageBackend = 1
)

// Enum value maps for StorageBackend.
var (
	StorageBackend_name = map[int32]string{
		0: "STORAGE_BACKEND_COUCHSTORE",
		1: "STORAGE_BACKEND_MAGMA",
	}
	StorageBackend_value = map[string]int32{
		"STORAGE_BACKEND_COUCHSTORE": 0,
		"STORAGE_BACKEND_MAGMA":      1,
	}
)

func (x StorageBackend) Enum() *StorageBackend {
	p := new(StorageBackend)
	*p = x
	return p
}

func (x StorageBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[3].Descriptor()
}

func (StorageBackend) Type() protoreflect.EnumType {
	return &file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[3]
}

func (x StorageBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageBackend.Descriptor instead.
func (StorageBackend) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{3}
}

type ConflictResolutionType int32

const (
	ConflictResolutionType_CONFLICT_RESOLUTION_TYPE_TIMESTAMP       ConflictResolutionType = 0
	ConflictResolutionType_CONFLICT_RESOLUTION_TYPE_SEQUENCE_NUMBER ConflictResolutionType = 1
	ConflictResolutionType_CONFLICT_RESOLUTION_TYPE_CUSTOM          ConflictResolutionType = 2
)

// Enum value maps for ConflictResolutionType.
var (
	ConflictResolutionType_name = map[int32]string{
		0: "CONFLICT_RESOLUTION_TYPE_TIMESTAMP",
		1: "CONFLICT_RESOLUTION_TYPE_SEQUENCE_NUMBER",
		2: "CONFLICT_RESOLUTION_TYPE_CUSTOM",
	}
	ConflictResolutionType_value = map[string]int32{
		"CONFLICT_RESOLUTION_TYPE_TIMESTAMP":       0,
		"CONFLICT_RESOLUTION_TYPE_SEQUENCE_NUMBER": 1,
		"CONFLICT_RESOLUTION_TYPE_CUSTOM":          2,
	}
)

func (x ConflictResolutionType) Enum() *ConflictResolutionType {
	p := new(ConflictResolutionType)
	*p = x
	return p
}

func (x ConflictResolutionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictResolutionType) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[4].Descriptor()
}

func (ConflictResolutionType) Type() protoreflect.EnumType {
	return &file_couchbase_admin_bucket_v1_bucket_proto_enumTypes[4]
}

func (x ConflictResolutionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictResolutionType.Descriptor instead.
func (ConflictResolutionType) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{4}
}

type ListBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{0}
}

type ListBucketsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Buckets       []*ListBucketsResponse_Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{1}
}

func (x *ListBucketsResponse) GetBuckets() []*ListBucketsResponse_Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type CreateBucketRequest struct {
	state                             protoimpl.MessageState  `protogen:"open.v1"`
	BucketName                        string                  `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	BucketType                        BucketType              `protobuf:"varint,2,opt,name=bucket_type,json=bucketType,proto3,enum=couchbase.admin.bucket.v1.BucketType" json:"bucket_type,omitempty"`
	RamQuotaMb                        *uint64                 `protobuf:"varint,3,opt,name=ram_quota_mb,json=ramQuotaMb,proto3,oneof" json:"ram_quota_mb,omitempty"`
	NumReplicas                       *uint32                 `protobuf:"varint,4,opt,name=num_replicas,json=numReplicas,proto3,oneof" json:"num_replicas,omitempty"`
	FlushEnabled                      *bool                   `protobuf:"varint,5,opt,name=flush_enabled,json=flushEnabled,proto3,oneof" json:"flush_enabled,omitempty"`
	ReplicaIndexes                    *bool                   `protobuf:"varint,6,opt,name=replica_indexes,json=replicaIndexes,proto3,oneof" json:"replica_indexes,omitempty"`
	EvictionMode                      *EvictionMode           `protobuf:"varint,7,opt,name=eviction_mode,json=evictionMode,proto3,enum=couchbase.admin.bucket.v1.EvictionMode,oneof" json:"eviction_mode,omitempty"`
	MaxExpirySecs                     *uint32                 `protobuf:"varint,8,opt,name=max_expiry_secs,json=maxExpirySecs,proto3,oneof" json:"max_expiry_secs,omitempty"`
	CompressionMode                   *CompressionMode        `protobuf:"varint,9,opt,name=compression_mode,json=compressionMode,proto3,enum=couchbase.admin.bucket.v1.CompressionMode,oneof" json:"compression_mode,omitempty"`
	MinimumDurabilityLevel            *kv_v1.DurabilityLevel  `protobuf:"varint,10,opt,name=minimum_durability_level,json=minimumDurabilityLevel,proto3,enum=couchbase.kv.v1.DurabilityLevel,oneof" json:"minimum_durability_level,omitempty"`
	StorageBackend                    *StorageBackend         `protobuf:"varint,11,opt,name=storage_backend,json=storageBackend,proto3,enum=couchbase.admin.bucket.v1.StorageBackend,oneof" json:"storage_backend,omitempty"`
	ConflictResolutionType            *ConflictResolutionType `protobuf:"varint,12,opt,name=conflict_resolution_type,json=conflictResolutionType,proto3,enum=couchbase.admin.bucket.v1.ConflictResolutionType,oneof" json:"conflict_resolution_type,omitempty"`
	HistoryRetentionCollectionDefault *bool                   `protobuf:"varint,13,opt,name=history_retention_collection_default,json=historyRetentionCollectionDefault,proto3,oneof" json:"history_retention_collection_default,omitempty"`
	HistoryRetentionBytes             *uint64                 `protobuf:"varint,14,opt,name=history_retention_bytes,json=historyRetentionBytes,proto3,oneof" json:"history_retention_bytes,omitempty"`
	HistoryRetentionDurationSecs      *uint32                 `protobuf:"varint,15,opt,name=history_retention_duration_secs,json=historyRetentionDurationSecs,proto3,oneof" json:"history_retention_duration_secs,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *CreateBucketRequest) GetBucketType() BucketType {
	if x != nil {
		return x.BucketType
	}
	return BucketType_BUCKET_TYPE_COUCHBASE
}

func (x *CreateBucketRequest) GetRamQuotaMb() uint64 {
	if x != nil && x.RamQuotaMb != nil {
		return *x.RamQuotaMb
	}
	return 0
}

func (x *CreateBucketRequest) GetNumReplicas() uint32 {
	if x != nil && x.NumReplicas != nil {
		return *x.NumReplicas
	}
	return 0
}

func (x *CreateBucketRequest) GetFlushEnabled() bool {
	if x != nil && x.FlushEnabled != nil {
		return *x.FlushEnabled
	}
	return false
}

func (x *CreateBucketRequest) GetReplicaIndexes() bool {
	if x != nil && x.ReplicaIndexes != nil {
		return *x.ReplicaIndexes
	}
	return false
}

func (x *CreateBucketRequest) GetEvictionMode() EvictionMode {
	if x != nil && x.EvictionMode != nil {
		return *x.EvictionMode
	}
	return EvictionMode_EVICTION_MODE_FULL
}

func (x *CreateBucketRequest) GetMaxExpirySecs() uint32 {
	if x != nil && x.MaxExpirySecs != nil {
		return *x.MaxExpirySecs
	}
	return 0
}

func (x *CreateBucketRequest) GetCompressionMode() CompressionMode {
	if x != nil && x.CompressionMode != nil {
		return *x.CompressionMode
	}
	return CompressionMode_COMPRESSION_MODE_OFF
}

func (x *CreateBucketRequest) GetMinimumDurabilityLevel() kv_v1.DurabilityLevel {
	if x != nil && x.MinimumDurabilityLevel != nil {
		return *x.MinimumDurabilityLevel
	}
	return kv_v1.DurabilityLevel(0)
}

func (x *CreateBucketRequest) GetStorageBackend() StorageBackend {
	if x != nil && x.StorageBackend != nil {
		return *x.StorageBackend
	}
	return StorageBackend_STORAGE_BACKEND_COUCHSTORE
}

func (x *CreateBucketRequest) GetConflictResolutionType() ConflictResolutionType {
	if x != nil && x.ConflictResolutionType != nil {
		return *x.ConflictResolutionType
	}
	return ConflictResolutionType_CONFLICT_RESOLUTION_TYPE_TIMESTAMP
}

func (x *CreateBucketRequest) GetHistoryRetentionCollectionDefault() bool {
	if x != nil && x.HistoryRetentionCollectionDefault != nil {
		return *x.HistoryRetentionCollectionDefault
	}
	return false
}

func (x *CreateBucketRequest) GetHistoryRetentionBytes() uint64 {
	if x != nil && x.HistoryRetentionBytes != nil {
		return *x.HistoryRetentionBytes
	}
	return 0
}

func (x *CreateBucketRequest) GetHistoryRetentionDurationSecs() uint32 {
	if x != nil && x.HistoryRetentionDurationSecs != nil {
		return *x.HistoryRetentionDurationSecs
	}
	return 0
}

type CreateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketUuid    string                 `protobuf:"bytes,1,opt,name=bucket_uuid,json=bucketUuid,proto3" json:"bucket_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResponse) Reset() {
	*x = CreateBucketResponse{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResponse) ProtoMessage() {}

func (x *CreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBucketResponse) GetBucketUuid() string {
	if x != nil {
		return x.BucketUuid
	}
	return ""
}

type UpdateBucketRequest struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	BucketName                        string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	RamQuotaMb                        *uint64                `protobuf:"varint,2,opt,name=ram_quota_mb,json=ramQuotaMb,proto3,oneof" json:"ram_quota_mb,omitempty"`
	NumReplicas                       *uint32                `protobuf:"varint,3,opt,name=num_replicas,json=numReplicas,proto3,oneof" json:"num_replicas,omitempty"`
	FlushEnabled                      *bool                  `protobuf:"varint,4,opt,name=flush_enabled,json=flushEnabled,proto3,oneof" json:"flush_enabled,omitempty"`
	EvictionMode                      *EvictionMode          `protobuf:"varint,5,opt,name=eviction_mode,json=evictionMode,proto3,enum=couchbase.admin.bucket.v1.EvictionMode,oneof" json:"eviction_mode,omitempty"`
	MaxExpirySecs                     *uint32                `protobuf:"varint,6,opt,name=max_expiry_secs,json=maxExpirySecs,proto3,oneof" json:"max_expiry_secs,omitempty"`
	CompressionMode                   *CompressionMode       `protobuf:"varint,7,opt,name=compression_mode,json=compressionMode,proto3,enum=couchbase.admin.bucket.v1.CompressionMode,oneof" json:"compression_mode,omitempty"`
	MinimumDurabilityLevel            *kv_v1.DurabilityLevel `protobuf:"varint,8,opt,name=minimum_durability_level,json=minimumDurabilityLevel,proto3,enum=couchbase.kv.v1.DurabilityLevel,oneof" json:"minimum_durability_level,omitempty"`
	HistoryRetentionCollectionDefault *bool                  `protobuf:"varint,10,opt,name=history_retention_collection_default,json=historyRetentionCollectionDefault,proto3,oneof" json:"history_retention_collection_default,omitempty"`
	HistoryRetentionBytes             *uint64                `protobuf:"varint,11,opt,name=history_retention_bytes,json=historyRetentionBytes,proto3,oneof" json:"history_retention_bytes,omitempty"`
	HistoryRetentionDurationSecs      *uint32                `protobuf:"varint,12,opt,name=history_retention_duration_secs,json=historyRetentionDurationSecs,proto3,oneof" json:"history_retention_duration_secs,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *UpdateBucketRequest) Reset() {
	*x = UpdateBucketRequest{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBucketRequest) ProtoMessage() {}

func (x *UpdateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBucketRequest.ProtoReflect.Descriptor instead.
func (*UpdateBucketRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *UpdateBucketRequest) GetRamQuotaMb() uint64 {
	if x != nil && x.RamQuotaMb != nil {
		return *x.RamQuotaMb
	}
	return 0
}

func (x *UpdateBucketRequest) GetNumReplicas() uint32 {
	if x != nil && x.NumReplicas != nil {
		return *x.NumReplicas
	}
	return 0
}

func (x *UpdateBucketRequest) GetFlushEnabled() bool {
	if x != nil && x.FlushEnabled != nil {
		return *x.FlushEnabled
	}
	return false
}

func (x *UpdateBucketRequest) GetEvictionMode() EvictionMode {
	if x != nil && x.EvictionMode != nil {
		return *x.EvictionMode
	}
	return EvictionMode_EVICTION_MODE_FULL
}

func (x *UpdateBucketRequest) GetMaxExpirySecs() uint32 {
	if x != nil && x.MaxExpirySecs != nil {
		return *x.MaxExpirySecs
	}
	return 0
}

func (x *UpdateBucketRequest) GetCompressionMode() CompressionMode {
	if x != nil && x.CompressionMode != nil {
		return *x.CompressionMode
	}
	return CompressionMode_COMPRESSION_MODE_OFF
}

func (x *UpdateBucketRequest) GetMinimumDurabilityLevel() kv_v1.DurabilityLevel {
	if x != nil && x.MinimumDurabilityLevel != nil {
		return *x.MinimumDurabilityLevel
	}
	return kv_v1.DurabilityLevel(0)
}

func (x *UpdateBucketRequest) GetHistoryRetentionCollectionDefault() bool {
	if x != nil && x.HistoryRetentionCollectionDefault != nil {
		return *x.HistoryRetentionCollectionDefault
	}
	return false
}

func (x *UpdateBucketRequest) GetHistoryRetentionBytes() uint64 {
	if x != nil && x.HistoryRetentionBytes != nil {
		return *x.HistoryRetentionBytes
	}
	return 0
}

func (x *UpdateBucketRequest) GetHistoryRetentionDurationSecs() uint32 {
	if x != nil && x.HistoryRetentionDurationSecs != nil {
		return *x.HistoryRetentionDurationSecs
	}
	return 0
}

type UpdateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBucketResponse) Reset() {
	*x = UpdateBucketResponse{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBucketResponse) ProtoMessage() {}

func (x *UpdateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBucketResponse.ProtoReflect.Descriptor instead.
func (*UpdateBucketResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{5}
}

type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type DeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketResponse) Reset() {
	*x = DeleteBucketResponse{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResponse) ProtoMessage() {}

func (x *DeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{7}
}

type FlushBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushBucketRequest) Reset() {
	*x = FlushBucketRequest{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushBucketRequest) ProtoMessage() {}

func (x *FlushBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushBucketRequest.ProtoReflect.Descriptor instead.
func (*FlushBucketRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{8}
}

func (x *FlushBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type FlushBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushBucketResponse) Reset() {
	*x = FlushBucketResponse{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushBucketResponse) ProtoMessage() {}

func (x *FlushBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushBucketResponse.ProtoReflect.Descriptor instead.
func (*FlushBucketResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{9}
}

type ListBucketsResponse_Bucket struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	BucketName                        string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	FlushEnabled                      bool                   `protobuf:"varint,2,opt,name=flush_enabled,json=flushEnabled,proto3" json:"flush_enabled,omitempty"`
	RamQuotaMb                        uint64                 `protobuf:"varint,3,opt,name=ram_quota_mb,json=ramQuotaMb,proto3" json:"ram_quota_mb,omitempty"`
	NumReplicas                       uint32                 `protobuf:"varint,4,opt,name=num_replicas,json=numReplicas,proto3" json:"num_replicas,omitempty"`
	ReplicaIndexes                    bool                   `protobuf:"varint,5,opt,name=replica_indexes,json=replicaIndexes,proto3" json:"replica_indexes,omitempty"`
	BucketType                        BucketType             `protobuf:"varint,6,opt,name=bucket_type,json=bucketType,proto3,enum=couchbase.admin.bucket.v1.BucketType" json:"bucket_type,omitempty"`
	EvictionMode                      EvictionMode           `protobuf:"varint,7,opt,name=eviction_mode,json=evictionMode,proto3,enum=couchbase.admin.bucket.v1.EvictionMode" json:"eviction_mode,omitempty"`
	MaxExpirySecs                     uint32                 `protobuf:"varint,8,opt,name=max_expiry_secs,json=maxExpirySecs,proto3" json:"max_expiry_secs,omitempty"`
	CompressionMode                   CompressionMode        `protobuf:"varint,9,opt,name=compression_mode,json=compressionMode,proto3,enum=couchbase.admin.bucket.v1.CompressionMode" json:"compression_mode,omitempty"`
	MinimumDurabilityLevel            *kv_v1.DurabilityLevel `protobuf:"varint,10,opt,name=minimum_durability_level,json=minimumDurabilityLevel,proto3,enum=couchbase.kv.v1.DurabilityLevel,oneof" json:"minimum_durability_level,omitempty"`
	StorageBackend                    *StorageBackend        `protobuf:"varint,11,opt,name=storage_backend,json=storageBackend,proto3,enum=couchbase.admin.bucket.v1.StorageBackend,oneof" json:"storage_backend,omitempty"`
	ConflictResolutionType            ConflictResolutionType `protobuf:"varint,12,opt,name=conflict_resolution_type,json=conflictResolutionType,proto3,enum=couchbase.admin.bucket.v1.ConflictResolutionType" json:"conflict_resolution_type,omitempty"`
	HistoryRetentionCollectionDefault *bool                  `protobuf:"varint,13,opt,name=history_retention_collection_default,json=historyRetentionCollectionDefault,proto3,oneof" json:"history_retention_collection_default,omitempty"`
	HistoryRetentionBytes             *uint64                `protobuf:"varint,14,opt,name=history_retention_bytes,json=historyRetentionBytes,proto3,oneof" json:"history_retention_bytes,omitempty"`
	HistoryRetentionDurationSecs      *uint32                `protobuf:"varint,15,opt,name=history_retention_duration_secs,json=historyRetentionDurationSecs,proto3,oneof" json:"history_retention_duration_secs,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ListBucketsResponse_Bucket) Reset() {
	*x = ListBucketsResponse_Bucket{}
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse_Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse_Bucket) ProtoMessage() {}

func (x *ListBucketsResponse_Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse_Bucket.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse_Bucket) Descriptor() ([]byte, []int) {
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListBucketsResponse_Bucket) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *ListBucketsResponse_Bucket) GetFlushEnabled() bool {
	if x != nil {
		return x.FlushEnabled
	}
	return false
}

func (x *ListBucketsResponse_Bucket) GetRamQuotaMb() uint64 {
	if x != nil {
		return x.RamQuotaMb
	}
	return 0
}

func (x *ListBucketsResponse_Bucket) GetNumReplicas() uint32 {
	if x != nil {
		return x.NumReplicas
	}
	return 0
}

func (x *ListBucketsResponse_Bucket) GetReplicaIndexes() bool {
	if x != nil {
		return x.ReplicaIndexes
	}
	return false
}

func (x *ListBucketsResponse_Bucket) GetBucketType() BucketType {
	if x != nil {
		return x.BucketType
	}
	return BucketType_BUCKET_TYPE_COUCHBASE
}

func (x *ListBucketsResponse_Bucket) GetEvictionMode() EvictionMode {
	if x != nil {
		return x.EvictionMode
	}
	return EvictionMode_EVICTION_MODE_FULL
}

func (x *ListBucketsResponse_Bucket) GetMaxExpirySecs() uint32 {
	if x != nil {
		return x.MaxExpirySecs
	}
	return 0
}

func (x *ListBucketsResponse_Bucket) GetCompressionMode() CompressionMode {
	if x != nil {
		return x.CompressionMode
	}
	return CompressionMode_COMPRESSION_MODE_OFF
}

func (x *ListBucketsResponse_Bucket) GetMinimumDurabilityLevel() kv_v1.DurabilityLevel {
	if x != nil && x.MinimumDurabilityLevel != nil {
		return *x.MinimumDurabilityLevel
	}
	return kv_v1.DurabilityLevel(0)
}

func (x *ListBucketsResponse_Bucket) GetStorageBackend() StorageBackend {
	if x != nil && x.StorageBackend != nil {
		return *x.StorageBackend
	}
	return StorageBackend_STORAGE_BACKEND_COUCHSTORE
}

func (x *ListBucketsResponse_Bucket) GetConflictResolutionType() ConflictResolutionType {
	if x != nil {
		return x.ConflictResolutionType
	}
	return ConflictResolutionType_CONFLICT_RESOLUTION_TYPE_TIMESTAMP
}

func (x *ListBucketsResponse_Bucket) GetHistoryRetentionCollectionDefault() bool {
	if x != nil && x.HistoryRetentionCollectionDefault != nil {
		return *x.HistoryRetentionCollectionDefault
	}
	return false
}

func (x *ListBucketsResponse_Bucket) GetHistoryRetentionBytes() uint64 {
	if x != nil && x.HistoryRetentionBytes != nil {
		return *x.HistoryRetentionBytes
	}
	return 0
}

func (x *ListBucketsResponse_Bucket) GetHistoryRetentionDurationSecs() uint32 {
	if x != nil && x.HistoryRetentionDurationSecs != nil {
		return *x.HistoryRetentionDurationSecs
	}
	return 0
}

var File_couchbase_admin_bucket_v1_bucket_proto protoreflect.FileDescriptor

const file_couchbase_admin_bucket_v1_bucket_proto_rawDesc = "" +
	"\n" +
	"&couchbase/admin/bucket/v1/bucket.proto\x12\x19couchbase.admin.bucket.v1\x1a\x18couchbase/kv/v1/kv.proto\"\x14\n" +
	"\x12ListBucketsRequest\"\xda\t\n" +
	"\x13ListBucketsResponse\x12O\n" +
	"\abuckets\x18\x01 \x03(\v25.couchbase.admin.bucket.v1.ListBucketsResponse.BucketR\abuckets\x1a\xf1\b\n" +
	"\x06Bucket\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12#\n" +
	"\rflush_enabled\x18\x02 \x01(\bR\fflushEnabled\x12 \n" +
	"\fram_quota_mb\x18\x03 \x01(\x04R\n" +
	"ramQuotaMb\x12!\n" +
	"\fnum_replicas\x18\x04 \x01(\rR\vnumReplicas\x12'\n" +
	"\x0freplica_indexes\x18\x05 \x01(\bR\x0ereplicaIndexes\x12F\n" +
	"\vbucket_type\x18\x06 \x01(\x0e2%.couchbase.admin.bucket.v1.BucketTypeR\n" +
	"bucketType\x12L\n" +
	"\reviction_mode\x18\a \x01(\x0e2'.couchbase.admin.bucket.v1.EvictionModeR\fevictionMode\x12&\n" +
	"\x0fmax_expiry_secs\x18\b \x01(\rR\rmaxExpirySecs\x12U\n" +
	"\x10compression_mode\x18\t \x01(\x0e2*.couchbase.admin.bucket.v1.CompressionModeR\x0fcompressionMode\x12_\n" +
	"\x18minimum_durability_level\x18\n" +
	" \x01(\x0e2 .couchbase.kv.v1.DurabilityLevelH\x00R\x16minimumDurabilityLevel\x88\x01\x01\x12W\n" +
	"\x0fstorage_backend\x18\v \x01(\x0e2).couchbase.admin.bucket.v1.StorageBackendH\x01R\x0estorageBackend\x88\x01\x01\x12k\n" +
	"\x18conflict_resolution_type\x18\f \x01(\x0e21.couchbase.admin.bucket.v1.ConflictResolutionTypeR\x16conflictResolutionType\x12T\n" +
	"$history_retention_collection_default\x18\r \x01(\bH\x02R!historyRetentionCollectionDefault\x88\x01\x01\x12;\n" +
	"\x17history_retention_bytes\x18\x0e \x01(\x04H\x03R\x15historyRetentionBytes\x88\x01\x01\x12J\n" +
	"\x1fhistory_retention_duration_secs\x18\x0f \x01(\rH\x04R\x1chistoryRetentionDurationSecs\x88\x01\x01B\x1b\n" +
	"\x19_minimum_durability_levelB\x12\n" +
	"\x10_storage_backendB'\n" +
	"%_history_retention_collection_defaultB\x1a\n" +
	"\x18_history_retention_bytesB\"\n" +
	" _history_retention_duration_secs\"\xc6\n" +
	"\n" +
	"\x13CreateBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12F\n" +
	"\vbucket_type\x18\x02 \x01(\x0e2%.couchbase.admin.bucket.v1.BucketTypeR\n" +
	"bucketType\x12%\n" +
	"\fram_quota_mb\x18\x03 \x01(\x04H\x00R\n" +
	"ramQuotaMb\x88\x01\x01\x12&\n" +
	"\fnum_replicas\x18\x04 \x01(\rH\x01R\vnumReplicas\x88\x01\x01\x12(\n" +
	"\rflush_enabled\x18\x05 \x01(\bH\x02R\fflushEnabled\x88\x01\x01\x12,\n" +
	"\x0freplica_indexes\x18\x06 \x01(\bH\x03R\x0ereplicaIndexes\x88\x01\x01\x12Q\n" +
	"\reviction_mode\x18\a \x01(\x0e2'.couchbase.admin.bucket.v1.EvictionModeH\x04R\fevictionMode\x88\x01\x01\x12+\n" +
	"\x0fmax_expiry_secs\x18\b \x01(\rH\x05R\rmaxExpirySecs\x88\x01\x01\x12Z\n" +
	"\x10compression_mode\x18\t \x01(\x0e2*.couchbase.admin.bucket.v1.CompressionModeH\x06R\x0fcompressionMode\x88\x01\x01\x12_\n" +
	"\x18minimum_durability_level\x18\n" +
	" \x01(\x0e2 .couchbase.kv.v1.DurabilityLevelH\aR\x16minimumDurabilityLevel\x88\x01\x01\x12W\n" +
	"\x0fstorage_backend\x18\v \x01(\x0e2).couchbase.admin.bucket.v1.StorageBackendH\bR\x0estorageBackend\x88\x01\x01\x12p\n" +
	"\x18conflict_resolution_type\x18\f \x01(\x0e21.couchbase.admin.bucket.v1.ConflictResolutionTypeH\tR\x16conflictResolutionType\x88\x01\x01\x12T\n" +
	"$history_retention_collection_default\x18\r \x01(\bH\n" +
	"R!historyRetentionCollectionDefault\x88\x01\x01\x12;\n" +
	"\x17history_retention_bytes\x18\x0e \x01(\x04H\vR\x15historyRetentionBytes\x88\x01\x01\x12J\n" +
	"\x1fhistory_retention_duration_secs\x18\x0f \x01(\rH\fR\x1chistoryRetentionDurationSecs\x88\x01\x01B\x0f\n" +
	"\r_ram_quota_mbB\x0f\n" +
	"\r_num_replicasB\x10\n" +
	"\x0e_flush_enabledB\x12\n" +
	"\x10_replica_indexesB\x10\n" +
	"\x0e_eviction_modeB\x12\n" +
	"\x10_max_expiry_secsB\x13\n" +
	"\x11_compression_modeB\x1b\n" +
	"\x19_minimum_durability_levelB\x12\n" +
	"\x10_storage_backendB\x1b\n" +
	"\x19_conflict_resolution_typeB'\n" +
	"%_history_retention_collection_defaultB\x1a\n" +
	"\x18_history_retention_bytesB\"\n" +
	" _history_retention_duration_secs\"7\n" +
	"\x14CreateBucketResponse\x12\x1f\n" +
	"\vbucket_uuid\x18\x01 \x01(\tR\n" +
	"bucketUuid\"\xc0\a\n" +
	"\x13UpdateBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12%\n" +
	"\fram_quota_mb\x18\x02 \x01(\x04H\x00R\n" +
	"ramQuotaMb\x88\x01\x01\x12&\n" +
	"\fnum_replicas\x18\x03 \x01(\rH\x01R\vnumReplicas\x88\x01\x01\x12(\n" +
	"\rflush_enabled\x18\x04 \x01(\bH\x02R\fflushEnabled\x88\x01\x01\x12Q\n" +
	"\reviction_mode\x18\x05 \x01(\x0e2'.couchbase.admin.bucket.v1.EvictionModeH\x03R\fevictionMode\x88\x01\x01\x12+\n" +
	"\x0fmax_expiry_secs\x18\x06 \x01(\rH\x04R\rmaxExpirySecs\x88\x01\x01\x12Z\n" +
	"\x10compression_mode\x18\a \x01(\x0e2*.couchbase.admin.bucket.v1.CompressionModeH\x05R\x0fcompressionMode\x88\x01\x01\x12_\n" +
	"\x18minimum_durability_level\x18\b \x01(\x0e2 .couchbase.kv.v1.DurabilityLevelH\x06R\x16minimumDurabilityLevel\x88\x01\x01\x12T\n" +
	"$history_retention_collection_default\x18\n" +
	" \x01(\bH\aR!historyRetentionCollectionDefault\x88\x01\x01\x12;\n" +
	"\x17history_retention_bytes\x18\v \x01(\x04H\bR\x15historyRetentionBytes\x88\x01\x01\x12J\n" +
	"\x1fhistory_retention_duration_secs\x18\f \x01(\rH\tR\x1chistoryRetentionDurationSecs\x88\x01\x01B\x0f\n" +
	"\r_ram_quota_mbB\x0f\n" +
	"\r_num_replicasB\x10\n" +
	"\x0e_flush_enabledB\x10\n" +
	"\x0e_eviction_modeB\x12\n" +
	"\x10_max_expiry_secsB\x13\n" +
	"\x11_compression_modeB\x1b\n" +
	"\x19_minimum_durability_levelB'\n" +
	"%_history_retention_collection_defaultB\x1a\n" +
	"\x18_history_retention_bytesB\"\n" +
	" _history_retention_duration_secs\"\x16\n" +
	"\x14UpdateBucketResponse\"6\n" +
	"\x13DeleteBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\"\x16\n" +
	"\x14DeleteBucketResponse\"5\n" +
	"\x12FlushBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\"\x15\n" +
	"\x13FlushBucketResponse*B\n" +
	"\n" +
	"BucketType\x12\x19\n" +
	"\x15BUCKET_TYPE_COUCHBASE\x10\x00\x12\x19\n" +
	"\x15BUCKET_TYPE_EPHEMERAL\x10\x01*\x81\x01\n" +
	"\fEvictionMode\x12\x16\n" +
	"\x12EVICTION_MODE_FULL\x10\x00\x12#\n" +
	"\x1fEVICTION_MODE_NOT_RECENTLY_USED\x10\x01\x12\x1c\n" +
	"\x18EVICTION_MODE_VALUE_ONLY\x10\x02\x12\x16\n" +
	"\x12EVICTION_MODE_NONE\x10\x03*f\n" +
	"\x0fCompressionMode\x12\x18\n" +
	"\x14COMPRESSION_MODE_OFF\x10\x00\x12\x1c\n" +
	"\x18COMPRESSION_MODE_PASSIVE\x10\x01\x12\x1b\n" +
	"\x17COMPRESSION_MODE_ACTIVE\x10\x02*K\n" +
	"\x0eStorageBackend\x12\x1e\n" +
	"\x1aSTORAGE_BACKEND_COUCHSTORE\x10\x00\x12\x19\n" +
	"\x15STORAGE_BACKEND_MAGMA\x10\x01*\x93\x01\n" +
	"\x16ConflictResolutionType\x12&\n" +
	"\"CONFLICT_RESOLUTION_TYPE_TIMESTAMP\x10\x00\x12,\n" +
	"(CONFLICT_RESOLUTION_TYPE_SEQUENCE_NUMBER\x10\x01\x12#\n" +
	"\x1fCONFLICT_RESOLUTION_TYPE_CUSTOM\x10\x022\xcd\x04\n" +
	"\x12BucketAdminService\x12n\n" +
	"\vListBuckets\x12-.couchbase.admin.bucket.v1.ListBucketsRequest\x1a..couchbase.admin.bucket.v1.ListBucketsResponse\"\x00\x12q\n" +
	"\fCreateBucket\x12..couchbase.admin.bucket.v1.CreateBucketRequest\x1a/.couchbase.admin.bucket.v1.CreateBucketResponse\"\x00\x12q\n" +
	"\fUpdateBucket\x12..couchbase.admin.bucket.v1.UpdateBucketRequest\x1a/.couchbase.admin.bucket.v1.UpdateBucketResponse\"\x00\x12q\n" +
	"\fDeleteBucket\x12..couchbase.admin.bucket.v1.DeleteBucketRequest\x1a/.couchbase.admin.bucket.v1.DeleteBucketResponse\"\x00\x12n\n" +
	"\vFlushBucket\x12-.couchbase.admin.bucket.v1.FlushBucketRequest\x1a..couchbase.admin.bucket.v1.FlushBucketResponse\"\x00B\x97\x02\n" +
	"1com.couchbase.client.protostellar.admin.bucket.v1P\x01ZLgithub.com/couchbase/goprotostellar/genproto/admin_bucket_v1;admin_bucket_v1\xaa\x02&Couchbase.Protostellar.Admin.Bucket.V1\xca\x020Couchbase\\Protostellar\\Generated\\Admin\\Bucket\\V1\xea\x025Couchbase::Protostellar::Generated::Admin::Bucket::V1b\x06proto3"

var (
	file_couchbase_admin_bucket_v1_bucket_proto_rawDescOnce sync.Once
	file_couchbase_admin_bucket_v1_bucket_proto_rawDescData []byte
)

func file_couchbase_admin_bucket_v1_bucket_proto_rawDescGZIP() []byte {
	file_couchbase_admin_bucket_v1_bucket_proto_rawDescOnce.Do(func() {
		file_couchbase_admin_bucket_v1_bucket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couchbase_admin_bucket_v1_bucket_proto_rawDesc), len(file_couchbase_admin_bucket_v1_bucket_proto_rawDesc)))
	})
	return file_couchbase_admin_bucket_v1_bucket_proto_rawDescData
}

var file_couchbase_admin_bucket_v1_bucket_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_couchbase_admin_bucket_v1_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_couchbase_admin_bucket_v1_bucket_proto_goTypes = []any{
	(BucketType)(0),                    // 0: couchbase.admin.bucket.v1.BucketType
	(EvictionMode)(0),                  // 1: couchbase.admin.bucket.v1.EvictionMode
	(CompressionMode)(0),               // 2: couchbase.admin.bucket.v1.CompressionMode
	(StorageBackend)(0),                // 3: couchbase.admin.bucket.v1.StorageBackend
	(ConflictResolutionType)(0),        // 4: couchbase.admin.bucket.v1.ConflictResolutionType
	(*ListBucketsRequest)(nil),         // 5: couchbase.admin.bucket.v1.ListBucketsRequest
	(*ListBucketsResponse)(nil),        // 6: couchbase.admin.bucket.v1.ListBucketsResponse
	(*CreateBucketRequest)(nil),        // 7: couchbase.admin.bucket.v1.CreateBucketRequest
	(*CreateBucketResponse)(nil),       // 8: couchbase.admin.bucket.v1.CreateBucketResponse
	(*UpdateBucketRequest)(nil),        // 9: couchbase.admin.bucket.v1.UpdateBucketRequest
	(*UpdateBucketResponse)(nil),       // 10: couchbase.admin.bucket.v1.UpdateBucketResponse
	(*DeleteBucketRequest)(nil),        // 11: couchbase.admin.bucket.v1.DeleteBucketRequest
	(*DeleteBucketResponse)(nil),       // 12: couchbase.admin.bucket.v1.DeleteBucketResponse
	(*FlushBucketRequest)(nil),         // 13: couchbase.admin.bucket.v1.FlushBucketRequest
	(*FlushBucketResponse)(nil),        // 14: couchbase.admin.bucket.v1.FlushBucketResponse
	(*ListBucketsResponse_Bucket)(nil), // 15: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket
	(kv_v1.DurabilityLevel)(0),         // 16: couchbase.kv.v1.DurabilityLevel
}
var file_couchbase_admin_bucket_v1_bucket_proto_depIdxs = []int32{
	15, // 0: couchbase.admin.bucket.v1.ListBucketsResponse.buckets:type_name -> couchbase.admin.bucket.v1.ListBucketsResponse.Bucket
	0,  // 1: couchbase.admin.bucket.v1.CreateBucketRequest.bucket_type:type_name -> couchbase.admin.bucket.v1.BucketType
	1,  // 2: couchbase.admin.bucket.v1.CreateBucketRequest.eviction_mode:type_name -> couchbase.admin.bucket.v1.EvictionMode
	2,  // 3: couchbase.admin.bucket.v1.CreateBucketRequest.compression_mode:type_name -> couchbase.admin.bucket.v1.CompressionMode
	16, // 4: couchbase.admin.bucket.v1.CreateBucketRequest.minimum_durability_level:type_name -> couchbase.kv.v1.DurabilityLevel
	3,  // 5: couchbase.admin.bucket.v1.CreateBucketRequest.storage_backend:type_name -> couchbase.admin.bucket.v1.StorageBackend
	4,  // 6: couchbase.admin.bucket.v1.CreateBucketRequest.conflict_resolution_type:type_name -> couchbase.admin.bucket.v1.ConflictResolutionType
	1,  // 7: couchbase.admin.bucket.v1.UpdateBucketRequest.eviction_mode:type_name -> couchbase.admin.bucket.v1.EvictionMode
	2,  // 8: couchbase.admin.bucket.v1.UpdateBucketRequest.compression_mode:type_name -> couchbase.admin.bucket.v1.CompressionMode
	16, // 9: couchbase.admin.bucket.v1.UpdateBucketRequest.minimum_durability_level:type_name -> couchbase.kv.v1.DurabilityLevel
	0,  // 10: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket.bucket_type:type_name -> couchbase.admin.bucket.v1.BucketType
	1,  // 11: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket.eviction_mode:type_name -> couchbase.admin.bucket.v1.EvictionMode
	2,  // 12: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket.compression_mode:type_name -> couchbase.admin.bucket.v1.CompressionMode
	16, // 13: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket.minimum_durability_level:type_name -> couchbase.kv.v1.DurabilityLevel
	3,  // 14: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket.storage_backend:type_name -> couchbase.admin.bucket.v1.StorageBackend
	4,  // 15: couchbase.admin.bucket.v1.ListBucketsResponse.Bucket.conflict_resolution_type:type_name -> couchbase.admin.bucket.v1.ConflictResolutionType
	5,  // 16: couchbase.admin.bucket.v1.BucketAdminService.ListBuckets:input_type -> couchbase.admin.bucket.v1.ListBucketsRequest
	7,  // 17: couchbase.admin.bucket.v1.BucketAdminService.CreateBucket:input_type -> couchbase.admin.bucket.v1.CreateBucketRequest
	9,  // 18: couchbase.admin.bucket.v1.BucketAdminService.UpdateBucket:input_type -> couchbase.admin.bucket.v1.UpdateBucketRequest
	11, // 19: couchbase.admin.bucket.v1.BucketAdminService.DeleteBucket:input_type -> couchbase.admin.bucket.v1.DeleteBucketRequest
	13, // 20: couchbase.admin.bucket.v1.BucketAdminService.FlushBucket:input_type -> couchbase.admin.bucket.v1.FlushBucketRequest
	6,  // 21: couchbase.admin.bucket.v1.BucketAdminService.ListBuckets:output_type -> couchbase.admin.bucket.v1.ListBucketsResponse
	8,  // 22: couchbase.admin.bucket.v1.BucketAdminService.CreateBucket:output_type -> couchbase.admin.bucket.v1.CreateBucketResponse
	10, // 23: couchbase.admin.bucket.v1.BucketAdminService.UpdateBucket:output_type -> couchbase.admin.bucket.v1.UpdateBucketResponse
	12, // 24: couchbase.admin.bucket.v1.BucketAdminService.DeleteBucket:output_type -> couchbase.admin.bucket.v1.DeleteBucketResponse
	14, // 25: couchbase.admin.bucket.v1.BucketAdminService.FlushBucket:output_type -> couchbase.admin.bucket.v1.FlushBucketResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_couchbase_admin_bucket_v1_bucket_proto_init() }
func file_couchbase_admin_bucket_v1_bucket_proto_init() {
	if File_couchbase_admin_bucket_v1_bucket_proto != nil {
		return
	}
	file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[2].OneofWrappers = []any{}
	file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[4].OneofWrappers = []any{}
	file_couchbase_admin_bucket_v1_bucket_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couchbase_admin_bucket_v1_bucket_proto_rawDesc), len(file_couchbase_admin_bucket_v1_bucket_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couchbase_admin_bucket_v1_bucket_proto_goTypes,
		DependencyIndexes: file_couchbase_admin_bucket_v1_bucket_proto_depIdxs,
		EnumInfos:         file_couchbase_admin_bucket_v1_bucket_proto_enumTypes,
		MessageInfos:      file_couchbase_admin_bucket_v1_bucket_proto_msgTypes,
	}.Build()
	File_couchbase_admin_bucket_v1_bucket_proto = out.File
	file_couchbase_admin_bucket_v1_bucket_proto_goTypes = nil
	file_couchbase_admin_bucket_v1_bucket_proto_depIdxs = nil
}
