// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: couchbase/view/v1/view.proto

package view_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewQueryRequest_ScanConsistency int32

const (
	ViewQueryRequest_SCAN_CONSISTENCY_NOT_BOUNDED  ViewQueryRequest_ScanConsistency = 0
	ViewQueryRequest_SCAN_CONSISTENCY_REQUEST_PLUS ViewQueryRequest_ScanConsistency = 1
	ViewQueryRequest_SCAN_CONSISTENCY_UPDATE_AFTER ViewQueryRequest_ScanConsistency = 2
)

// Enum value maps for ViewQueryRequest_ScanConsistency.
var (
	ViewQueryRequest_ScanConsistency_name = map[int32]string{
		0: "SCAN_CONSISTENCY_NOT_BOUNDED",
		1: "SCAN_CONSISTENCY_REQUEST_PLUS",
		2: "SCAN_CONSISTENCY_UPDATE_AFTER",
	}
	ViewQueryRequest_ScanConsistency_value = map[string]int32{
		"SCAN_CONSISTENCY_NOT_BOUNDED":  0,
		"SCAN_CONSISTENCY_REQUEST_PLUS": 1,
		"SCAN_CONSISTENCY_UPDATE_AFTER": 2,
	}
)

func (x ViewQueryRequest_ScanConsistency) Enum() *ViewQueryRequest_ScanConsistency {
	p := new(ViewQueryRequest_ScanConsistency)
	*p = x
	return p
}

func (x ViewQueryRequest_ScanConsistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewQueryRequest_ScanConsistency) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_view_v1_view_proto_enumTypes[0].Descriptor()
}

func (ViewQueryRequest_ScanConsistency) Type() protoreflect.EnumType {
	return &file_couchbase_view_v1_view_proto_enumTypes[0]
}

func (x ViewQueryRequest_ScanConsistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewQueryRequest_ScanConsistency.Descriptor instead.
func (ViewQueryRequest_ScanConsistency) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{0, 0}
}

type ViewQueryRequest_ErrorMode int32

const (
	ViewQueryRequest_ERROR_MODE_CONTINUE ViewQueryRequest_ErrorMode = 0
	ViewQueryRequest_ERROR_MODE_STOP     ViewQueryRequest_ErrorMode = 1
)

// Enum value maps for ViewQueryRequest_ErrorMode.
var (
	ViewQueryRequest_ErrorMode_name = map[int32]string{
		0: "ERROR_MODE_CONTINUE",
		1: "ERROR_MODE_STOP",
	}
	ViewQueryRequest_ErrorMode_value = map[string]int32{
		"ERROR_MODE_CONTINUE": 0,
		"ERROR_MODE_STOP":     1,
	}
)

func (x ViewQueryRequest_ErrorMode) Enum() *ViewQueryRequest_ErrorMode {
	p := new(ViewQueryRequest_ErrorMode)
	*p = x
	return p
}

func (x ViewQueryRequest_ErrorMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewQueryRequest_ErrorMode) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_view_v1_view_proto_enumTypes[1].Descriptor()
}

func (ViewQueryRequest_ErrorMode) Type() protoreflect.EnumType {
	return &file_couchbase_view_v1_view_proto_enumTypes[1]
}

func (x ViewQueryRequest_ErrorMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewQueryRequest_ErrorMode.Descriptor instead.
func (ViewQueryRequest_ErrorMode) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{0, 1}
}

type ViewQueryRequest_Namespace int32

const (
	ViewQueryRequest_NAMESPACE_PRODUCTION  ViewQueryRequest_Namespace = 0
	ViewQueryRequest_NAMESPACE_DEVELOPMENT ViewQueryRequest_Namespace = 1
)

// Enum value maps for ViewQueryRequest_Namespace.
var (
	ViewQueryRequest_Namespace_name = map[int32]string{
		0: "NAMESPACE_PRODUCTION",
		1: "NAMESPACE_DEVELOPMENT",
	}
	ViewQueryRequest_Namespace_value = map[string]int32{
		"NAMESPACE_PRODUCTION":  0,
		"NAMESPACE_DEVELOPMENT": 1,
	}
)

func (x ViewQueryRequest_Namespace) Enum() *ViewQueryRequest_Namespace {
	p := new(ViewQueryRequest_Namespace)
	*p = x
	return p
}

func (x ViewQueryRequest_Namespace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewQueryRequest_Namespace) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_view_v1_view_proto_enumTypes[2].Descriptor()
}

func (ViewQueryRequest_Namespace) Type() protoreflect.EnumType {
	return &file_couchbase_view_v1_view_proto_enumTypes[2]
}

func (x ViewQueryRequest_Namespace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewQueryRequest_Namespace.Descriptor instead.
func (ViewQueryRequest_Namespace) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{0, 2}
}

type ViewQueryRequest_Order int32

const (
	ViewQueryRequest_ORDER_ASCENDING  ViewQueryRequest_Order = 0
	ViewQueryRequest_ORDER_DESCENDING ViewQueryRequest_Order = 1
)

// Enum value maps for ViewQueryRequest_Order.
var (
	ViewQueryRequest_Order_name = map[int32]string{
		0: "ORDER_ASCENDING",
		1: "ORDER_DESCENDING",
	}
	ViewQueryRequest_Order_value = map[string]int32{
		"ORDER_ASCENDING":  0,
		"ORDER_DESCENDING": 1,
	}
)

func (x ViewQueryRequest_Order) Enum() *ViewQueryRequest_Order {
	p := new(ViewQueryRequest_Order)
	*p = x
	return p
}

func (x ViewQueryRequest_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewQueryRequest_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_couchbase_view_v1_view_proto_enumTypes[3].Descriptor()
}

func (ViewQueryRequest_Order) Type() protoreflect.EnumType {
	return &file_couchbase_view_v1_view_proto_enumTypes[3]
}

func (x ViewQueryRequest_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewQueryRequest_Order.Descriptor instead.
func (ViewQueryRequest_Order) EnumDescriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{0, 3}
}

type ViewQueryRequest struct {
	state              protoimpl.MessageState            `protogen:"open.v1"`
	BucketName         string                            `protobuf:"bytes,8,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	DesignDocumentName string                            `protobuf:"bytes,1,opt,name=design_document_name,json=designDocumentName,proto3" json:"design_document_name,omitempty"`
	ViewName           string                            `protobuf:"bytes,2,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	Skip               *uint32                           `protobuf:"varint,3,opt,name=skip,proto3,oneof" json:"skip,omitempty"`
	Limit              *uint32                           `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	ScanConsistency    *ViewQueryRequest_ScanConsistency `protobuf:"varint,5,opt,name=scan_consistency,json=scanConsistency,proto3,enum=couchbase.view.v1.ViewQueryRequest_ScanConsistency,oneof" json:"scan_consistency,omitempty"`
	Reduce             *bool                             `protobuf:"varint,6,opt,name=reduce,proto3,oneof" json:"reduce,omitempty"`
	Group              *bool                             `protobuf:"varint,7,opt,name=group,proto3,oneof" json:"group,omitempty"`
	GroupLevel         *uint32                           `protobuf:"varint,9,opt,name=group_level,json=groupLevel,proto3,oneof" json:"group_level,omitempty"`
	Key                []byte                            `protobuf:"bytes,10,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Keys               [][]byte                          `protobuf:"bytes,11,rep,name=keys,proto3" json:"keys,omitempty"`
	StartKey           []byte                            `protobuf:"bytes,12,opt,name=start_key,json=startKey,proto3,oneof" json:"start_key,omitempty"`
	EndKey             []byte                            `protobuf:"bytes,13,opt,name=end_key,json=endKey,proto3,oneof" json:"end_key,omitempty"`
	InclusiveEnd       *bool                             `protobuf:"varint,14,opt,name=inclusive_end,json=inclusiveEnd,proto3,oneof" json:"inclusive_end,omitempty"`
	StartKeyDocId      *string                           `protobuf:"bytes,15,opt,name=start_key_doc_id,json=startKeyDocId,proto3,oneof" json:"start_key_doc_id,omitempty"`
	EndKeyDocId        *string                           `protobuf:"bytes,16,opt,name=end_key_doc_id,json=endKeyDocId,proto3,oneof" json:"end_key_doc_id,omitempty"`
	OnError            *ViewQueryRequest_ErrorMode       `protobuf:"varint,17,opt,name=on_error,json=onError,proto3,enum=couchbase.view.v1.ViewQueryRequest_ErrorMode,oneof" json:"on_error,omitempty"`
	Debug              *bool                             `protobuf:"varint,18,opt,name=debug,proto3,oneof" json:"debug,omitempty"`
	Namespace          *ViewQueryRequest_Namespace       `protobuf:"varint,19,opt,name=namespace,proto3,enum=couchbase.view.v1.ViewQueryRequest_Namespace,oneof" json:"namespace,omitempty"`
	Order              *ViewQueryRequest_Order           `protobuf:"varint,20,opt,name=order,proto3,enum=couchbase.view.v1.ViewQueryRequest_Order,oneof" json:"order,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ViewQueryRequest) Reset() {
	*x = ViewQueryRequest{}
	mi := &file_couchbase_view_v1_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewQueryRequest) ProtoMessage() {}

func (x *ViewQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_view_v1_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewQueryRequest.ProtoReflect.Descriptor instead.
func (*ViewQueryRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{0}
}

func (x *ViewQueryRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *ViewQueryRequest) GetDesignDocumentName() string {
	if x != nil {
		return x.DesignDocumentName
	}
	return ""
}

func (x *ViewQueryRequest) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *ViewQueryRequest) GetSkip() uint32 {
	if x != nil && x.Skip != nil {
		return *x.Skip
	}
	return 0
}

func (x *ViewQueryRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ViewQueryRequest) GetScanConsistency() ViewQueryRequest_ScanConsistency {
	if x != nil && x.ScanConsistency != nil {
		return *x.ScanConsistency
	}
	return ViewQueryRequest_SCAN_CONSISTENCY_NOT_BOUNDED
}

func (x *ViewQueryRequest) GetReduce() bool {
	if x != nil && x.Reduce != nil {
		return *x.Reduce
	}
	return false
}

func (x *ViewQueryRequest) GetGroup() bool {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return false
}

func (x *ViewQueryRequest) GetGroupLevel() uint32 {
	if x != nil && x.GroupLevel != nil {
		return *x.GroupLevel
	}
	return 0
}

func (x *ViewQueryRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ViewQueryRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ViewQueryRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ViewQueryRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ViewQueryRequest) GetInclusiveEnd() bool {
	if x != nil && x.InclusiveEnd != nil {
		return *x.InclusiveEnd
	}
	return false
}

func (x *ViewQueryRequest) GetStartKeyDocId() string {
	if x != nil && x.StartKeyDocId != nil {
		return *x.StartKeyDocId
	}
	return ""
}

func (x *ViewQueryRequest) GetEndKeyDocId() string {
	if x != nil && x.EndKeyDocId != nil {
		return *x.EndKeyDocId
	}
	return ""
}

func (x *ViewQueryRequest) GetOnError() ViewQueryRequest_ErrorMode {
	if x != nil && x.OnError != nil {
		return *x.OnError
	}
	return ViewQueryRequest_ERROR_MODE_CONTINUE
}

func (x *ViewQueryRequest) GetDebug() bool {
	if x != nil && x.Debug != nil {
		return *x.Debug
	}
	return false
}

func (x *ViewQueryRequest) GetNamespace() ViewQueryRequest_Namespace {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ViewQueryRequest_NAMESPACE_PRODUCTION
}

func (x *ViewQueryRequest) GetOrder() ViewQueryRequest_Order {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ViewQueryRequest_ORDER_ASCENDING
}

type ViewQueryResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Rows          []*ViewQueryResponse_Row    `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	MetaData      *ViewQueryResponse_MetaData `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3,oneof" json:"meta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewQueryResponse) Reset() {
	*x = ViewQueryResponse{}
	mi := &file_couchbase_view_v1_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewQueryResponse) ProtoMessage() {}

func (x *ViewQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_view_v1_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewQueryResponse.ProtoReflect.Descriptor instead.
func (*ViewQueryResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{1}
}

func (x *ViewQueryResponse) GetRows() []*ViewQueryResponse_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ViewQueryResponse) GetMetaData() *ViewQueryResponse_MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type ViewQueryResponse_Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewQueryResponse_Row) Reset() {
	*x = ViewQueryResponse_Row{}
	mi := &file_couchbase_view_v1_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewQueryResponse_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewQueryResponse_Row) ProtoMessage() {}

func (x *ViewQueryResponse_Row) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_view_v1_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewQueryResponse_Row.ProtoReflect.Descriptor instead.
func (*ViewQueryResponse_Row) Descriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ViewQueryResponse_Row) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ViewQueryResponse_Row) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ViewQueryResponse_Row) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ViewQueryResponse_MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRows     uint64                 `protobuf:"varint,1,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	Debug         []byte                 `protobuf:"bytes,2,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewQueryResponse_MetaData) Reset() {
	*x = ViewQueryResponse_MetaData{}
	mi := &file_couchbase_view_v1_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewQueryResponse_MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewQueryResponse_MetaData) ProtoMessage() {}

func (x *ViewQueryResponse_MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_view_v1_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewQueryResponse_MetaData.ProtoReflect.Descriptor instead.
func (*ViewQueryResponse_MetaData) Descriptor() ([]byte, []int) {
	return file_couchbase_view_v1_view_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ViewQueryResponse_MetaData) GetTotalRows() uint64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *ViewQueryResponse_MetaData) GetDebug() []byte {
	if x != nil {
		return x.Debug
	}
	return nil
}

var File_couchbase_view_v1_view_proto protoreflect.FileDescriptor

const file_couchbase_view_v1_view_proto_rawDesc = "" +
	"\n" +
	"\x1ccouchbase/view/v1/view.proto\x12\x11couchbase.view.v1\"\xec\n" +
	"\n" +
	"\x10ViewQueryRequest\x12\x1f\n" +
	"\vbucket_name\x18\b \x01(\tR\n" +
	"bucketName\x120\n" +
	"\x14design_document_name\x18\x01 \x01(\tR\x12designDocumentName\x12\x1b\n" +
	"\tview_name\x18\x02 \x01(\tR\bviewName\x12\x17\n" +
	"\x04skip\x18\x03 \x01(\rH\x00R\x04skip\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x01R\x05limit\x88\x01\x01\x12c\n" +
	"\x10scan_consistency\x18\x05 \x01(\x0e23.couchbase.view.v1.ViewQueryRequest.ScanConsistencyH\x02R\x0fscanConsistency\x88\x01\x01\x12\x1b\n" +
	"\x06reduce\x18\x06 \x01(\bH\x03R\x06reduce\x88\x01\x01\x12\x19\n" +
	"\x05group\x18\a \x01(\bH\x04R\x05group\x88\x01\x01\x12$\n" +
	"\vgroup_level\x18\t \x01(\rH\x05R\n" +
	"groupLevel\x88\x01\x01\x12\x15\n" +
	"\x03key\x18\n" +
	" \x01(\fH\x06R\x03key\x88\x01\x01\x12\x12\n" +
	"\x04keys\x18\v \x03(\fR\x04keys\x12 \n" +
	"\tstart_key\x18\f \x01(\fH\aR\bstartKey\x88\x01\x01\x12\x1c\n" +
	"\aend_key\x18\r \x01(\fH\bR\x06endKey\x88\x01\x01\x12(\n" +
	"\rinclusive_end\x18\x0e \x01(\bH\tR\finclusiveEnd\x88\x01\x01\x12,\n" +
	"\x10start_key_doc_id\x18\x0f \x01(\tH\n" +
	"R\rstartKeyDocId\x88\x01\x01\x12(\n" +
	"\x0eend_key_doc_id\x18\x10 \x01(\tH\vR\vendKeyDocId\x88\x01\x01\x12M\n" +
	"\bon_error\x18\x11 \x01(\x0e2-.couchbase.view.v1.ViewQueryRequest.ErrorModeH\fR\aonError\x88\x01\x01\x12\x19\n" +
	"\x05debug\x18\x12 \x01(\bH\rR\x05debug\x88\x01\x01\x12P\n" +
	"\tnamespace\x18\x13 \x01(\x0e2-.couchbase.view.v1.ViewQueryRequest.NamespaceH\x0eR\tnamespace\x88\x01\x01\x12D\n" +
	"\x05order\x18\x14 \x01(\x0e2).couchbase.view.v1.ViewQueryRequest.OrderH\x0fR\x05order\x88\x01\x01\"y\n" +
	"\x0fScanConsistency\x12 \n" +
	"\x1cSCAN_CONSISTENCY_NOT_BOUNDED\x10\x00\x12!\n" +
	"\x1dSCAN_CONSISTENCY_REQUEST_PLUS\x10\x01\x12!\n" +
	"\x1dSCAN_CONSISTENCY_UPDATE_AFTER\x10\x02\"9\n" +
	"\tErrorMode\x12\x17\n" +
	"\x13ERROR_MODE_CONTINUE\x10\x00\x12\x13\n" +
	"\x0fERROR_MODE_STOP\x10\x01\"@\n" +
	"\tNamespace\x12\x18\n" +
	"\x14NAMESPACE_PRODUCTION\x10\x00\x12\x19\n" +
	"\x15NAMESPACE_DEVELOPMENT\x10\x01\"2\n" +
	"\x05Order\x12\x13\n" +
	"\x0fORDER_ASCENDING\x10\x00\x12\x14\n" +
	"\x10ORDER_DESCENDING\x10\x01B\a\n" +
	"\x05_skipB\b\n" +
	"\x06_limitB\x13\n" +
	"\x11_scan_consistencyB\t\n" +
	"\a_reduceB\b\n" +
	"\x06_groupB\x0e\n" +
	"\f_group_levelB\x06\n" +
	"\x04_keyB\f\n" +
	"\n" +
	"_start_keyB\n" +
	"\n" +
	"\b_end_keyB\x10\n" +
	"\x0e_inclusive_endB\x13\n" +
	"\x11_start_key_doc_idB\x11\n" +
	"\x0f_end_key_doc_idB\v\n" +
	"\t_on_errorB\b\n" +
	"\x06_debugB\f\n" +
	"\n" +
	"_namespaceB\b\n" +
	"\x06_order\"\xb0\x02\n" +
	"\x11ViewQueryResponse\x12<\n" +
	"\x04rows\x18\x01 \x03(\v2(.couchbase.view.v1.ViewQueryResponse.RowR\x04rows\x12O\n" +
	"\tmeta_data\x18\x02 \x01(\v2-.couchbase.view.v1.ViewQueryResponse.MetaDataH\x00R\bmetaData\x88\x01\x01\x1a=\n" +
	"\x03Row\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x1a?\n" +
	"\bMetaData\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x01 \x01(\x04R\ttotalRows\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\fR\x05debugB\f\n" +
	"\n" +
	"_meta_data2i\n" +
	"\vViewService\x12Z\n" +
	"\tViewQuery\x12#.couchbase.view.v1.ViewQueryRequest\x1a$.couchbase.view.v1.ViewQueryResponse\"\x000\x01B\xe6\x01\n" +
	")com.couchbase.client.protostellar.view.v1P\x01Z<github.com/couchbase/goprotostellar/genproto/view_v1;view_v1\xaa\x02\x1eCouchbase.Protostellar.View.V1\xca\x02(Couchbase\\Protostellar\\Generated\\View\\V1\xea\x02,Couchbase::Protostellar::Generated::View::V1b\x06proto3"

var (
	file_couchbase_view_v1_view_proto_rawDescOnce sync.Once
	file_couchbase_view_v1_view_proto_rawDescData []byte
)

func file_couchbase_view_v1_view_proto_rawDescGZIP() []byte {
	file_couchbase_view_v1_view_proto_rawDescOnce.Do(func() {
		file_couchbase_view_v1_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couchbase_view_v1_view_proto_rawDesc), len(file_couchbase_view_v1_view_proto_rawDesc)))
	})
	return file_couchbase_view_v1_view_proto_rawDescData
}

var file_couchbase_view_v1_view_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_couchbase_view_v1_view_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_couchbase_view_v1_view_proto_goTypes = []any{
	(ViewQueryRequest_ScanConsistency)(0), // 0: couchbase.view.v1.ViewQueryRequest.ScanConsistency
	(ViewQueryRequest_ErrorMode)(0),       // 1: couchbase.view.v1.ViewQueryRequest.ErrorMode
	(ViewQueryRequest_Namespace)(0),       // 2: couchbase.view.v1.ViewQueryRequest.Namespace
	(ViewQueryRequest_Order)(0),           // 3: couchbase.view.v1.ViewQueryRequest.Order
	(*ViewQueryRequest)(nil),              // 4: couchbase.view.v1.ViewQueryRequest
	(*ViewQueryResponse)(nil),             // 5: couchbase.view.v1.ViewQueryResponse
	(*ViewQueryResponse_Row)(nil),         // 6: couchbase.view.v1.ViewQueryResponse.Row
	(*ViewQueryResponse_MetaData)(nil),    // 7: couchbase.view.v1.ViewQueryResponse.MetaData
}
var file_couchbase_view_v1_view_proto_depIdxs = []int32{
	0, // 0: couchbase.view.v1.ViewQueryRequest.scan_consistency:type_name -> couchbase.view.v1.ViewQueryRequest.ScanConsistency
	1, // 1: couchbase.view.v1.ViewQueryRequest.on_error:type_name -> couchbase.view.v1.ViewQueryRequest.ErrorMode
	2, // 2: couchbase.view.v1.ViewQueryRequest.namespace:type_name -> couchbase.view.v1.ViewQueryRequest.Namespace
	3, // 3: couchbase.view.v1.ViewQueryRequest.order:type_name -> couchbase.view.v1.ViewQueryRequest.Order
	6, // 4: couchbase.view.v1.ViewQueryResponse.rows:type_name -> couchbase.view.v1.ViewQueryResponse.Row
	7, // 5: couchbase.view.v1.ViewQueryResponse.meta_data:type_name -> couchbase.view.v1.ViewQueryResponse.MetaData
	4, // 6: couchbase.view.v1.ViewService.ViewQuery:input_type -> couchbase.view.v1.ViewQueryRequest
	5, // 7: couchbase.view.v1.ViewService.ViewQuery:output_type -> couchbase.view.v1.ViewQueryResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_couchbase_view_v1_view_proto_init() }
func file_couchbase_view_v1_view_proto_init() {
	if File_couchbase_view_v1_view_proto != nil {
		return
	}
	file_couchbase_view_v1_view_proto_msgTypes[0].OneofWrappers = []any{}
	file_couchbase_view_v1_view_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couchbase_view_v1_view_proto_rawDesc), len(file_couchbase_view_v1_view_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couchbase_view_v1_view_proto_goTypes,
		DependencyIndexes: file_couchbase_view_v1_view_proto_depIdxs,
		EnumInfos:         file_couchbase_view_v1_view_proto_enumTypes,
		MessageInfos:      file_couchbase_view_v1_view_proto_msgTypes,
	}.Build()
	File_couchbase_view_v1_view_proto = out.File
	file_couchbase_view_v1_view_proto_goTypes = nil
	file_couchbase_view_v1_view_proto_depIdxs = nil
}
