// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: couchbase/routing/v1/routing.proto

package routing_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutingEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerGroup   string                 `protobuf:"bytes,2,opt,name=server_group,json=serverGroup,proto3" json:"server_group,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingEndpoint) Reset() {
	*x = RoutingEndpoint{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingEndpoint) ProtoMessage() {}

func (x *RoutingEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingEndpoint.ProtoReflect.Descriptor instead.
func (*RoutingEndpoint) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingEndpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoutingEndpoint) GetServerGroup() string {
	if x != nil {
		return x.ServerGroup
	}
	return ""
}

func (x *RoutingEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DataRoutingEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointIdx   uint32                 `protobuf:"varint,1,opt,name=endpoint_idx,json=endpointIdx,proto3" json:"endpoint_idx,omitempty"`
	LocalVbuckets []uint32               `protobuf:"varint,2,rep,packed,name=local_vbuckets,json=localVbuckets,proto3" json:"local_vbuckets,omitempty"`
	GroupVbuckets []uint32               `protobuf:"varint,3,rep,packed,name=group_vbuckets,json=groupVbuckets,proto3" json:"group_vbuckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRoutingEndpoint) Reset() {
	*x = DataRoutingEndpoint{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRoutingEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRoutingEndpoint) ProtoMessage() {}

func (x *DataRoutingEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRoutingEndpoint.ProtoReflect.Descriptor instead.
func (*DataRoutingEndpoint) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *DataRoutingEndpoint) GetEndpointIdx() uint32 {
	if x != nil {
		return x.EndpointIdx
	}
	return 0
}

func (x *DataRoutingEndpoint) GetLocalVbuckets() []uint32 {
	if x != nil {
		return x.LocalVbuckets
	}
	return nil
}

func (x *DataRoutingEndpoint) GetGroupVbuckets() []uint32 {
	if x != nil {
		return x.GroupVbuckets
	}
	return nil
}

type VbucketDataRoutingStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*DataRoutingEndpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	NumVbuckets   uint32                 `protobuf:"varint,3,opt,name=num_vbuckets,json=numVbuckets,proto3" json:"num_vbuckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VbucketDataRoutingStrategy) Reset() {
	*x = VbucketDataRoutingStrategy{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VbucketDataRoutingStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VbucketDataRoutingStrategy) ProtoMessage() {}

func (x *VbucketDataRoutingStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VbucketDataRoutingStrategy.ProtoReflect.Descriptor instead.
func (*VbucketDataRoutingStrategy) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *VbucketDataRoutingStrategy) GetEndpoints() []*DataRoutingEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *VbucketDataRoutingStrategy) GetNumVbuckets() uint32 {
	if x != nil {
		return x.NumVbuckets
	}
	return 0
}

type QueryRoutingEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointIdx   uint32                 `protobuf:"varint,1,opt,name=endpoint_idx,json=endpointIdx,proto3" json:"endpoint_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRoutingEndpoint) Reset() {
	*x = QueryRoutingEndpoint{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRoutingEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoutingEndpoint) ProtoMessage() {}

func (x *QueryRoutingEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoutingEndpoint.ProtoReflect.Descriptor instead.
func (*QueryRoutingEndpoint) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRoutingEndpoint) GetEndpointIdx() uint32 {
	if x != nil {
		return x.EndpointIdx
	}
	return 0
}

type QueryRouting struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Endpoints     []*QueryRoutingEndpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRouting) Reset() {
	*x = QueryRouting{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRouting) ProtoMessage() {}

func (x *QueryRouting) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRouting.ProtoReflect.Descriptor instead.
func (*QueryRouting) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRouting) GetEndpoints() []*QueryRoutingEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ViewsRoutingEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointIdx   uint32                 `protobuf:"varint,1,opt,name=endpoint_idx,json=endpointIdx,proto3" json:"endpoint_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewsRoutingEndpoint) Reset() {
	*x = ViewsRoutingEndpoint{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewsRoutingEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsRoutingEndpoint) ProtoMessage() {}

func (x *ViewsRoutingEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsRoutingEndpoint.ProtoReflect.Descriptor instead.
func (*ViewsRoutingEndpoint) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{5}
}

func (x *ViewsRoutingEndpoint) GetEndpointIdx() uint32 {
	if x != nil {
		return x.EndpointIdx
	}
	return 0
}

type ViewsRouting struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Endpoints     []*ViewsRoutingEndpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewsRouting) Reset() {
	*x = ViewsRouting{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewsRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsRouting) ProtoMessage() {}

func (x *ViewsRouting) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsRouting.ProtoReflect.Descriptor instead.
func (*ViewsRouting) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{6}
}

func (x *ViewsRouting) GetEndpoints() []*ViewsRoutingEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type WatchRoutingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the specific bucket that will be accessed.
	BucketName    *string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3,oneof" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoutingRequest) Reset() {
	*x = WatchRoutingRequest{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingRequest) ProtoMessage() {}

func (x *WatchRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingRequest.ProtoReflect.Descriptor instead.
func (*WatchRoutingRequest) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRoutingRequest) GetBucketName() string {
	if x != nil && x.BucketName != nil {
		return *x.BucketName
	}
	return ""
}

type WatchRoutingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Represents the revision of this configuration.  The revision not being
	// included indicates that this configuration is not versioned.  Configuration
	// revisions can only be compared for responses from the same request values
	// (different buckets may have uniquely incremented revisions).  Revision
	// comparison is done in order of the revision data, for instance we may have
	// [major, minor, patch].  Revisions may be any number of values long, and any
	// missing values should be assumed as 0 (except in the completely empty case,
	// where it is considered unused).
	Revision []uint64 `protobuf:"varint,1,rep,packed,name=revision,proto3" json:"revision,omitempty"`
	// Represents a complete list of all endpoints that are available for this
	// cluster.
	Endpoints []*RoutingEndpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Types that are valid to be assigned to DataRouting:
	//
	//	*WatchRoutingResponse_VbucketDataRouting
	DataRouting   isWatchRoutingResponse_DataRouting `protobuf_oneof:"data_routing"`
	QueryRouting  *QueryRouting                      `protobuf:"bytes,4,opt,name=query_routing,json=queryRouting,proto3,oneof" json:"query_routing,omitempty"`
	ViewsRouting  *ViewsRouting                      `protobuf:"bytes,5,opt,name=views_routing,json=viewsRouting,proto3,oneof" json:"views_routing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRoutingResponse) Reset() {
	*x = WatchRoutingResponse{}
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRoutingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRoutingResponse) ProtoMessage() {}

func (x *WatchRoutingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_couchbase_routing_v1_routing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRoutingResponse.ProtoReflect.Descriptor instead.
func (*WatchRoutingResponse) Descriptor() ([]byte, []int) {
	return file_couchbase_routing_v1_routing_proto_rawDescGZIP(), []int{8}
}

func (x *WatchRoutingResponse) GetRevision() []uint64 {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *WatchRoutingResponse) GetEndpoints() []*RoutingEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *WatchRoutingResponse) GetDataRouting() isWatchRoutingResponse_DataRouting {
	if x != nil {
		return x.DataRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetVbucketDataRouting() *VbucketDataRoutingStrategy {
	if x != nil {
		if x, ok := x.DataRouting.(*WatchRoutingResponse_VbucketDataRouting); ok {
			return x.VbucketDataRouting
		}
	}
	return nil
}

func (x *WatchRoutingResponse) GetQueryRouting() *QueryRouting {
	if x != nil {
		return x.QueryRouting
	}
	return nil
}

func (x *WatchRoutingResponse) GetViewsRouting() *ViewsRouting {
	if x != nil {
		return x.ViewsRouting
	}
	return nil
}

type isWatchRoutingResponse_DataRouting interface {
	isWatchRoutingResponse_DataRouting()
}

type WatchRoutingResponse_VbucketDataRouting struct {
	VbucketDataRouting *VbucketDataRoutingStrategy `protobuf:"bytes,3,opt,name=vbucket_data_routing,json=vbucketDataRouting,proto3,oneof"`
}

func (*WatchRoutingResponse_VbucketDataRouting) isWatchRoutingResponse_DataRouting() {}

var File_couchbase_routing_v1_routing_proto protoreflect.FileDescriptor

const file_couchbase_routing_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\"couchbase/routing/v1/routing.proto\x12\x14couchbase.routing.v1\"^\n" +
	"\x0fRoutingEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fserver_group\x18\x02 \x01(\tR\vserverGroup\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x86\x01\n" +
	"\x13DataRoutingEndpoint\x12!\n" +
	"\fendpoint_idx\x18\x01 \x01(\rR\vendpointIdx\x12%\n" +
	"\x0elocal_vbuckets\x18\x02 \x03(\rR\rlocalVbuckets\x12%\n" +
	"\x0egroup_vbuckets\x18\x03 \x03(\rR\rgroupVbuckets\"\x88\x01\n" +
	"\x1aVbucketDataRoutingStrategy\x12G\n" +
	"\tendpoints\x18\x01 \x03(\v2).couchbase.routing.v1.DataRoutingEndpointR\tendpoints\x12!\n" +
	"\fnum_vbuckets\x18\x03 \x01(\rR\vnumVbuckets\"9\n" +
	"\x14QueryRoutingEndpoint\x12!\n" +
	"\fendpoint_idx\x18\x01 \x01(\rR\vendpointIdx\"X\n" +
	"\fQueryRouting\x12H\n" +
	"\tendpoints\x18\x01 \x03(\v2*.couchbase.routing.v1.QueryRoutingEndpointR\tendpoints\"9\n" +
	"\x14ViewsRoutingEndpoint\x12!\n" +
	"\fendpoint_idx\x18\x01 \x01(\rR\vendpointIdx\"X\n" +
	"\fViewsRouting\x12H\n" +
	"\tendpoints\x18\x01 \x03(\v2*.couchbase.routing.v1.ViewsRoutingEndpointR\tendpoints\"K\n" +
	"\x13WatchRoutingRequest\x12$\n" +
	"\vbucket_name\x18\x01 \x01(\tH\x00R\n" +
	"bucketName\x88\x01\x01B\x0e\n" +
	"\f_bucket_name\"\xad\x03\n" +
	"\x14WatchRoutingResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x03(\x04R\brevision\x12C\n" +
	"\tendpoints\x18\x02 \x03(\v2%.couchbase.routing.v1.RoutingEndpointR\tendpoints\x12d\n" +
	"\x14vbucket_data_routing\x18\x03 \x01(\v20.couchbase.routing.v1.VbucketDataRoutingStrategyH\x00R\x12vbucketDataRouting\x12L\n" +
	"\rquery_routing\x18\x04 \x01(\v2\".couchbase.routing.v1.QueryRoutingH\x01R\fqueryRouting\x88\x01\x01\x12L\n" +
	"\rviews_routing\x18\x05 \x01(\v2\".couchbase.routing.v1.ViewsRoutingH\x02R\fviewsRouting\x88\x01\x01B\x0e\n" +
	"\fdata_routingB\x10\n" +
	"\x0e_query_routingB\x10\n" +
	"\x0e_views_routing2{\n" +
	"\x0eRoutingService\x12i\n" +
	"\fWatchRouting\x12).couchbase.routing.v1.WatchRoutingRequest\x1a*.couchbase.routing.v1.WatchRoutingResponse\"\x000\x01B\xf8\x01\n" +
	",com.couchbase.client.protostellar.routing.v1P\x01ZBgithub.com/couchbase/goprotostellar/genproto/routing_v1;routing_v1\xaa\x02!Couchbase.Protostellar.Routing.V1\xca\x02+Couchbase\\Protostellar\\Generated\\Routing\\V1\xea\x02/Couchbase::Protostellar::Generated::Routing::V1b\x06proto3"

var (
	file_couchbase_routing_v1_routing_proto_rawDescOnce sync.Once
	file_couchbase_routing_v1_routing_proto_rawDescData []byte
)

func file_couchbase_routing_v1_routing_proto_rawDescGZIP() []byte {
	file_couchbase_routing_v1_routing_proto_rawDescOnce.Do(func() {
		file_couchbase_routing_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_couchbase_routing_v1_routing_proto_rawDesc), len(file_couchbase_routing_v1_routing_proto_rawDesc)))
	})
	return file_couchbase_routing_v1_routing_proto_rawDescData
}

var file_couchbase_routing_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_couchbase_routing_v1_routing_proto_goTypes = []any{
	(*RoutingEndpoint)(nil),            // 0: couchbase.routing.v1.RoutingEndpoint
	(*DataRoutingEndpoint)(nil),        // 1: couchbase.routing.v1.DataRoutingEndpoint
	(*VbucketDataRoutingStrategy)(nil), // 2: couchbase.routing.v1.VbucketDataRoutingStrategy
	(*QueryRoutingEndpoint)(nil),       // 3: couchbase.routing.v1.QueryRoutingEndpoint
	(*QueryRouting)(nil),               // 4: couchbase.routing.v1.QueryRouting
	(*ViewsRoutingEndpoint)(nil),       // 5: couchbase.routing.v1.ViewsRoutingEndpoint
	(*ViewsRouting)(nil),               // 6: couchbase.routing.v1.ViewsRouting
	(*WatchRoutingRequest)(nil),        // 7: couchbase.routing.v1.WatchRoutingRequest
	(*WatchRoutingResponse)(nil),       // 8: couchbase.routing.v1.WatchRoutingResponse
}
var file_couchbase_routing_v1_routing_proto_depIdxs = []int32{
	1, // 0: couchbase.routing.v1.VbucketDataRoutingStrategy.endpoints:type_name -> couchbase.routing.v1.DataRoutingEndpoint
	3, // 1: couchbase.routing.v1.QueryRouting.endpoints:type_name -> couchbase.routing.v1.QueryRoutingEndpoint
	5, // 2: couchbase.routing.v1.ViewsRouting.endpoints:type_name -> couchbase.routing.v1.ViewsRoutingEndpoint
	0, // 3: couchbase.routing.v1.WatchRoutingResponse.endpoints:type_name -> couchbase.routing.v1.RoutingEndpoint
	2, // 4: couchbase.routing.v1.WatchRoutingResponse.vbucket_data_routing:type_name -> couchbase.routing.v1.VbucketDataRoutingStrategy
	4, // 5: couchbase.routing.v1.WatchRoutingResponse.query_routing:type_name -> couchbase.routing.v1.QueryRouting
	6, // 6: couchbase.routing.v1.WatchRoutingResponse.views_routing:type_name -> couchbase.routing.v1.ViewsRouting
	7, // 7: couchbase.routing.v1.RoutingService.WatchRouting:input_type -> couchbase.routing.v1.WatchRoutingRequest
	8, // 8: couchbase.routing.v1.RoutingService.WatchRouting:output_type -> couchbase.routing.v1.WatchRoutingResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_couchbase_routing_v1_routing_proto_init() }
func file_couchbase_routing_v1_routing_proto_init() {
	if File_couchbase_routing_v1_routing_proto != nil {
		return
	}
	file_couchbase_routing_v1_routing_proto_msgTypes[7].OneofWrappers = []any{}
	file_couchbase_routing_v1_routing_proto_msgTypes[8].OneofWrappers = []any{
		(*WatchRoutingResponse_VbucketDataRouting)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_couchbase_routing_v1_routing_proto_rawDesc), len(file_couchbase_routing_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_couchbase_routing_v1_routing_proto_goTypes,
		DependencyIndexes: file_couchbase_routing_v1_routing_proto_depIdxs,
		MessageInfos:      file_couchbase_routing_v1_routing_proto_msgTypes,
	}.Build()
	File_couchbase_routing_v1_routing_proto = out.File
	file_couchbase_routing_v1_routing_proto_goTypes = nil
	file_couchbase_routing_v1_routing_proto_depIdxs = nil
}
